const CACHE_PREFIX='artisys-locadora-george-';
const CACHE=CACHE_PREFIX+'0.7.0-cloud-mobile-1';
const SHELL=['./','./index.html','./styles.css','./styles-p1.css','./styles-p2.css','./manifest.webmanifest','./src/cloud-app.mjs','./src/app.mjs','./src/api/client.mjs','./src/storage/repository.mjs','./src/storage/pwa-sqlite.mjs','./src/storage/cache-store.mjs','./src/storage/cloud-repository.mjs','./src/storage/offline-blob-store.mjs','./src/storage/attachment-store.mjs','./src/sync/cloud-sync.mjs','./src/sync/outbox.mjs','./src/sync/outbox-runner.mjs','./vendor/sqlite/sql-wasm.js','./vendor/sqlite/sql-wasm.wasm'];
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(SHELL)).then(()=>self.skipWaiting())));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key.startsWith(CACHE_PREFIX)&&key!==CACHE).map(key=>caches.delete(key)))).then(()=>self.clients.claim())));
function sameOrigin(url){return url.origin===self.location.origin;}
async function navigation(request){try{const response=await fetch(request);if(response.ok&&sameOrigin(new URL(response.url)))await (await caches.open(CACHE)).put('./index.html',response.clone());return response;}catch{const cached=await caches.match('./index.html');return cached||new Response('Offline',{status:503,headers:{'content-type':'text/plain; charset=utf-8'}});}}
async function staticAsset(request){const cached=await caches.match(request);if(cached)return cached;try{const response=await fetch(request);const url=new URL(request.url);if(response.ok&&sameOrigin(url)&&!url.pathname.startsWith('/api/'))await (await caches.open(CACHE)).put(request,response.clone());return response;}catch{return new Response('Offline',{status:503,headers:{'content-type':'text/plain; charset=utf-8'}});}}
self.addEventListener('fetch',event=>{const request=event.request,url=new URL(request.url);if(request.method!=='GET')return;if(url.pathname.startsWith('/api/'))return;if(!sameOrigin(url))return;if(request.mode==='navigate'){event.respondWith(navigation(request));return;}event.respondWith(staticAsset(request));});
