import test from 'node:test';
import assert from 'node:assert/strict';
import { FakeD1, seedOperationFixture } from './helpers/fake-d1.mjs';
import { handleParityCommandRoute } from '../cloudflare/api/parity-command-routes.mjs';
import { createRentalOperation } from '../cloudflare/domain/rentals.mjs';

function setup(role='admin'){const db=new FakeD1(),ids=seedOperationFixture(db),auth={installationId:ids.installationId,userId:ids.userId,deviceId:'WEB-PARITY',role,active:true};return{db,env:{DB:db},auth,...ids};}
function req(kind,{key='OP-PARITY',body={}}={}){return new Request(`https://app.test/api/v1/commands/${encodeURIComponent(kind)}`,{method:'POST',headers:{'content-type':'application/json','idempotency-key':key},body:JSON.stringify(body)});}
async function call(ctx,kind,opts={},auth=ctx.auth){const response=await handleParityCommandRoute(req(kind,opts),ctx.env,null,{auth});const body=await response.json();return{response,body};}
async function seedRental(ctx,id='LOC-PARITY'){return createRentalOperation({db:ctx.db,auth:ctx.auth},{id,customerId:ctx.customerId,vehicleId:ctx.vehicleId,pickupAt:'2026-10-01T10:00:00.000Z',returnAt:'2026-10-03T10:00:00.000Z',dailyRate:100,billingMode:'total'},`SEED-${id}`);}

test('commands require authentication and matching RBAC',async()=>{const ctx=setup();try{let result=await call(ctx,'expense.create',{body:{description:'Combustível',amount:50}},null);assert.equal(result.response.status,401);result=await call(ctx,'expense.create',{body:{description:'Combustível',amount:50}},{...ctx.auth,role:'vistoriador'});assert.equal(result.response.status,403);}finally{ctx.db.close();}});

test('expense create is idempotent and atomically creates ledger',async()=>{const ctx=setup();try{const opts={key:'EXP-ONE',body:{id:'DES-WEB-1',description:'Lavagem',category:'Operação',amount:80,dueAt:'2026-10-01',paid:true,vehicleId:ctx.vehicleId}};const first=await call(ctx,'expense.create',opts),second=await call(ctx,'expense.create',opts);assert.equal(first.response.status,201);assert.equal(second.response.status,200);assert.equal(second.body.replayed,true);assert.equal(ctx.db.scalar('SELECT COUNT(*) FROM expenses WHERE installation_id=? AND id=?',ctx.installationId,'DES-WEB-1'),1);assert.equal(ctx.db.scalar('SELECT COUNT(*) FROM ledger WHERE installation_id=? AND expense_id=?',ctx.installationId,'DES-WEB-1'),1);assert.equal(ctx.db.scalar('SELECT COUNT(*) FROM sync_changes WHERE installation_id=? AND operation_id=?',ctx.installationId,'EXP-ONE'),1);}finally{ctx.db.close();}});

test('billing plan and collection action are canonical and replay safe',async()=>{const ctx=setup();try{await seedRental(ctx);let result=await call(ctx,'billing.plan.create',{key:'PLAN-ONE',body:{id:'PLAN-WEB-1',rentalId:'LOC-PARITY',frequency:'monthly',amount:120,occurrences:2,firstDueAt:'2026-10-05',finePercent:2,interestMonthlyPercent:1}});assert.equal(result.response.status,201);assert.equal(ctx.db.scalar('SELECT COUNT(*) FROM billing_installments WHERE installation_id=? AND plan_id=?',ctx.installationId,'PLAN-WEB-1'),2);const installment=ctx.db.sqlite.prepare('SELECT id FROM billing_installments WHERE installation_id=? AND plan_id=? ORDER BY sequence LIMIT 1').get(ctx.installationId,'PLAN-WEB-1');result=await call(ctx,'collectionAction.create',{key:'COL-ONE',body:{id:'COL-WEB-1',installmentId:installment.id,channel:'WhatsApp',note:'Cobrança enviada'}});assert.equal(result.response.status,201);assert.equal(ctx.db.scalar('SELECT COUNT(*) FROM collection_actions WHERE installation_id=? AND id=?',ctx.installationId,'COL-WEB-1'),1);}finally{ctx.db.close();}});

test('maintenance schedule/start/complete updates vehicle and canonical cost exactly once',async()=>{const ctx=setup();try{let result=await call(ctx,'maintenance.create',{key:'MNT-CREATE',body:{id:'MNT-WEB-1',vehicleId:ctx.vehicleId,type:'Troca de óleo',dueAt:'2026-10-10',costEstimate:200}});assert.equal(result.response.status,201);result=await call(ctx,'maintenance.start',{key:'MNT-START',body:{id:'MNT-WEB-1'}});assert.equal(result.response.status,200);assert.equal(ctx.db.scalar('SELECT availability FROM vehicles WHERE installation_id=? AND id=?',ctx.installationId,ctx.vehicleId),'manutencao');result=await call(ctx,'maintenance.complete',{key:'MNT-END',body:{id:'MNT-WEB-1',cost:180,mileage:15000,notes:'Concluído'}});assert.equal(result.response.status,200);assert.equal(ctx.db.scalar('SELECT availability FROM vehicles WHERE installation_id=? AND id=?',ctx.installationId,ctx.vehicleId),'disponivel');assert.equal(ctx.db.scalar('SELECT mileage FROM vehicles WHERE installation_id=? AND id=?',ctx.installationId,ctx.vehicleId),15000);assert.equal(ctx.db.scalar('SELECT COUNT(*) FROM expenses WHERE installation_id=? AND category=?',ctx.installationId,'Manutenção'),1);const replay=await call(ctx,'maintenance.complete',{key:'MNT-END',body:{id:'MNT-WEB-1',cost:180,mileage:15000}});assert.equal(replay.body.replayed,true);assert.equal(ctx.db.scalar('SELECT COUNT(*) FROM expenses WHERE installation_id=? AND category=?',ctx.installationId,'Manutenção'),1);}finally{ctx.db.close();}});

test('contract template can be issued once as immutable historical output',async()=>{const ctx=setup();try{await seedRental(ctx);let result=await call(ctx,'contract.template.create',{key:'TPL-CREATE',body:{id:'TPL-WEB-1',name:'Padrão',body:'Contrato {{rentalId}} - {{customerName}}',isDefault:true}});assert.equal(result.response.status,201);result=await call(ctx,'contract.issue',{key:'ISSUE-ONE',body:{id:'ISS-WEB-1',rentalId:'LOC-PARITY',templateId:'TPL-WEB-1'}});assert.equal(result.response.status,201);assert.match(result.body.item.renderedText,/LOC-PARITY/);const replay=await call(ctx,'contract.issue',{key:'ISSUE-ONE',body:{id:'ISS-WEB-2',rentalId:'LOC-PARITY',templateId:'TPL-WEB-1'}});assert.equal(replay.body.replayed,true);assert.equal(ctx.db.scalar('SELECT COUNT(*) FROM issued_contracts WHERE installation_id=? AND rental_id=?',ctx.installationId,'LOC-PARITY'),1);}finally{ctx.db.close();}});

test('alert acknowledgement persists state map and emits delta',async()=>{const ctx=setup();try{const result=await call(ctx,'alert.acknowledge',{key:'ALT-ACK',body:{alertId:'rental-overdue:LOC-1'}});assert.equal(result.response.status,200);const raw=ctx.db.scalar('SELECT state_json FROM alert_state WHERE installation_id=? LIMIT 1',ctx.installationId),state=JSON.parse(raw);assert.ok(state['rental-overdue:LOC-1'].acknowledgedAt);assert.equal(ctx.db.scalar('SELECT COUNT(*) FROM sync_changes WHERE installation_id=? AND operation_id=?',ctx.installationId,'ALT-ACK'),1);}finally{ctx.db.close();}});
