const DEFAULT_TIMEOUT_MS=15_000;
export class ApiError extends Error{constructor(message,{status=0,code='api_error',details=null,cause=null}={}){super(message,{cause});this.name='ApiError';this.status=Number(status)||0;this.code=code;this.details=details;}}
function sleep(ms){return ms>0?new Promise(resolve=>setTimeout(resolve,ms)):Promise.resolve();}
function normalizeBaseUrl(value){const text=String(value??'').trim();return text.endsWith('/')?text.slice(0,-1):text;}
function resolveUrl(baseUrl,path){const text=String(path??'');if(/^https?:\/\//i.test(text))return text;if(baseUrl)return`${baseUrl}${text.startsWith('/')?'':'/'}${text}`;return text.startsWith('/')?text:`/${text}`;}
function isJson(response){return /(?:^|\/)json(?:;|$)/i.test(response.headers.get('content-type')??'')||/application\/[^;]+\+json/i.test(response.headers.get('content-type')??'');}
function retryable(method,operationId){return['GET','HEAD','OPTIONS'].includes(method)||Boolean(operationId);}
function mutating(method){return['POST','PUT','PATCH','DELETE'].includes(method);}

export function createApiClient({baseUrl='',fetchImpl=globalThis.fetch,timeoutMs=DEFAULT_TIMEOUT_MS,maxRetries=1,retryDelayMs=150,onUnauthorized=()=>{}}={}){
  if(typeof fetchImpl!=='function')throw new TypeError('fetchImpl_required');
  const origin=normalizeBaseUrl(baseUrl);let restoreGeneration=null;
  async function request(path,{method='GET',body,headers={},operationId=null,signal=null}={}){
    const verb=String(method).toUpperCase(),url=resolveUrl(origin,path),canRetry=retryable(verb,operationId);let attempt=0;
    while(true){
      const controller=!signal&&timeoutMs>0?new AbortController():null,timer=controller?setTimeout(()=>controller.abort(new DOMException('Request timed out','TimeoutError')),timeoutMs):null,requestHeaders=new Headers(headers);
      requestHeaders.set('accept','application/json');if(operationId)requestHeaders.set('idempotency-key',String(operationId));if(mutating(verb)&&restoreGeneration!=null)requestHeaders.set('x-locadora-restore-generation',String(restoreGeneration));
      let payload=body;if(body!==undefined&&body!==null&&!(body instanceof Blob)&&!(body instanceof ArrayBuffer)&&!ArrayBuffer.isView(body)&&typeof body!=='string'){requestHeaders.set('content-type','application/json');payload=JSON.stringify(body);}
      try{
        const response=await fetchImpl(url,{method:verb,headers:requestHeaders,body:payload,credentials:'include',signal:signal??controller?.signal,cache:'no-store'});let data=null;
        if(response.status!==204&&response.status!==205){if(isJson(response)){try{data=await response.json();}catch(error){throw new ApiError('invalid_json_response',{status:response.status,code:'invalid_response',cause:error});}}else if(response.ok)throw new ApiError('non_json_response',{status:response.status,code:'invalid_response'});}
        if(data?.restoreGeneration!=null)restoreGeneration=Number(data.restoreGeneration);
        if(!response.ok){const code=data?.error??`http_${response.status}`,error=new ApiError(data?.message??code,{status:response.status,code,details:data});if(response.status===401){try{await onUnauthorized(error);}catch{}}throw error;}
        return data;
      }catch(error){const networkError=!(error instanceof ApiError);if(networkError&&canRetry&&attempt<maxRetries){attempt++;await sleep(retryDelayMs);continue;}throw error;}finally{if(timer)clearTimeout(timer);}
    }
  }
  return Object.freeze({
    request,
    setRestoreGeneration:value=>{restoreGeneration=value==null?null:Number(value);},getRestoreGeneration:()=>restoreGeneration,
    async health(){return request('/api/v1/health');},
    async login(input){return request('/api/v1/auth/login',{method:'POST',body:input});},async firstAccess(input){return request('/api/v1/auth/first-access',{method:'POST',body:input});},async logout(){return request('/api/v1/auth/logout',{method:'POST'});},async session(){return request('/api/v1/auth/me');},
    async listDevices(){const result=await request('/api/v1/devices');return result?.devices??[];},async revokeDevice(id){return request(`/api/v1/devices/${encodeURIComponent(id)}/revoke`,{method:'POST'});},async revokeOtherSessions(){return request('/api/v1/sessions/revoke-others',{method:'POST'});},async revokeAllSessions(){return request('/api/v1/sessions/revoke-all',{method:'POST'});},
    async getAdminAudit(filters={}){const params=new URLSearchParams();for(const key of ['action','entityType','actorId','from','to','limit','offset'])if(filters[key]!==undefined&&filters[key]!==null&&String(filters[key])!=='')params.set(key,String(filters[key]));const suffix=params.toString();return request(`/api/v1/admin/audit${suffix?`?${suffix}`:''}`);},
    async getAdminSettings(){return request('/api/v1/admin/settings');},
    async getAdminDataInventory(){return request('/api/v1/admin/data-inventory');},
    async getOverviewSummary(){const result=await request('/api/v1/summary/overview');return result?.summary??{};},
    async getFinanceSummary(){const result=await request('/api/v1/summary/finance');return result?.summary??{};},
    async getFinanceReceivables({limit=30,offset=0,q=''}={}){const params=new URLSearchParams({limit:String(limit),offset:String(offset)});if(q)params.set('q',String(q));const result=await request(`/api/v1/summary/finance/receivables?${params.toString()}`);return{items:result?.items??[],pagination:result?.pagination??{limit,offset,nextOffset:null,hasMore:false,q}};},
    async updateAdminSettings(data,{expectedVersion}={}){return request('/api/v1/admin/settings',{method:'PATCH',body:{data,expectedVersion}});},
    async listCloudBackups(){const result=await request('/api/v1/backups');return result?.backups??[];},
    async createCloudBackup(){const result=await request('/api/v1/backups',{method:'POST'});return result?.backup??null;},
    async restoreCloudBackup(id,{password,confirmation='RESTAURAR'}={}){return request(`/api/v1/backups/${encodeURIComponent(id)}/restore`,{method:'POST',body:{password,confirmation}});},
    async importMigration(tables,{operationId='desktop:migration:seed'}={}){return request('/api/v1/migration/import',{method:'POST',body:{tables},operationId});},
    async listPage(resource,{limit=250,offset=0,q='',filters={},from='',to=''}={}){const params=new URLSearchParams({limit:String(limit),offset:String(offset)});if(q)params.set('q',String(q));if(from)params.set('from',String(from));if(to)params.set('to',String(to));for(const [key,value] of Object.entries(filters??{}))if(value!==undefined&&value!==null&&String(value)!=='')params.set(key,String(value));const result=await request(`/api/v1/${encodeURIComponent(resource)}?${params.toString()}`);return{items:result?.items??[],pagination:result?.pagination??{limit,offset,nextOffset:null,hasMore:false,q,filters,from,to}};},
    async list(resource,{pageSize=250,maxPages=100,q='',filters={},from='',to=''}={}){const items=[];let offset=0,pages=0;while(pages<Math.max(1,Number(maxPages)||100)){const result=await this.listPage(resource,{limit:pageSize,offset,q,filters,from,to}),batch=result?.items??[],pagination=result?.pagination??{};items.push(...batch);pages++;if(!pagination.hasMore||pagination.nextOffset==null||batch.length===0)break;offset=Number(pagination.nextOffset)||items.length;}return items;},async get(resource,id){const result=await request(`/api/v1/${encodeURIComponent(resource)}/${encodeURIComponent(id)}`);return result?.item??null;},async create(resource,data,{operationId}={}){const result=await request(`/api/v1/${encodeURIComponent(resource)}`,{method:'POST',body:data,operationId});return result?.item??null;},async update(resource,id,data,{expectedVersion,operationId}={}){const result=await request(`/api/v1/${encodeURIComponent(resource)}/${encodeURIComponent(id)}`,{method:'PATCH',body:{data,expectedVersion},operationId});return result?.item??null;},async remove(resource,id,{expectedVersion,operationId}={}){await request(`/api/v1/${encodeURIComponent(resource)}/${encodeURIComponent(id)}?expectedVersion=${encodeURIComponent(expectedVersion)}`,{method:'DELETE',operationId});return true;},
    async createRental(data,{operationId}={}){const result=await request('/api/v1/rentals',{method:'POST',body:data,operationId});return result?.item??result?.result??null;},async advanceRental(rentalId,data,{operationId}={}){const result=await request(`/api/v1/rentals/${encodeURIComponent(rentalId)}/advance`,{method:'POST',body:data,operationId});return result?.item??null;},async closeContinuousRental(rentalId,data,{operationId}={}){const result=await request(`/api/v1/rentals/${encodeURIComponent(rentalId)}/close-continuous`,{method:'POST',body:data,operationId});return result?.item??null;},async payRental(rentalId,data,{operationId}={}){const result=await request(`/api/v1/rentals/${encodeURIComponent(rentalId)}/payments`,{method:'POST',body:data,operationId});return result?.item??result?.result??null;},async payInstallment(installmentId,data,{operationId}={}){const result=await request(`/api/v1/billing/installments/${encodeURIComponent(installmentId)}/payments`,{method:'POST',body:data,operationId});return result?.item??result?.result??null;},async createInspection(data,{operationId}={}){const result=await request('/api/v1/inspections',{method:'POST',body:data,operationId});return result?.item??null;},async command(kind,data,{operationId}={}){const result=await request(`/api/v1/commands/${encodeURIComponent(kind)}`,{method:'POST',body:data,operationId});return result?.item??result?.result??result;},
    async pushSyncOperations(operations,{operationId=null}={}){const list=Array.isArray(operations)?operations:[],key=operationId??list[0]?.operationId;return request('/api/v1/sync/operations',{method:'POST',body:{operations:list,restoreGeneration},operationId:key});},async pullSyncChanges(after=0,limit=100){return request(`/api/v1/sync/changes?after=${encodeURIComponent(after)}&limit=${encodeURIComponent(limit)}`);},
    async uploadAttachment(id,{entityType,entityId,mimeType,body:fileBody,fileName=''}={}, {operationId}={}){const result=await request(`/api/v1/attachments/${encodeURIComponent(id)}?entityType=${encodeURIComponent(entityType)}&entityId=${encodeURIComponent(entityId)}`,{method:'PUT',body:fileBody,headers:{'content-type':mimeType,'x-file-name':fileName},operationId});return result?.item??null;},async deleteAttachment(id,{operationId}={}){await request(`/api/v1/attachments/${encodeURIComponent(id)}`,{method:'DELETE',operationId});return true;}
  });
}
