import { API_PREFIX, publicHealth } from './config.mjs';
import { handleAttachmentRoute,isAttachmentRoute } from './api/attachment-routes.mjs';
import { handleAuthRoute } from './api/auth-routes.mjs';
import { handleBillingRoute,isBillingOperationRoute } from './api/billing-routes.mjs';
import { handleInspectionRoute,isInspectionOperationRoute } from './api/inspection-routes.mjs';
import { handleRentalRoute,isRentalOperationRoute } from './api/rental-routes.mjs';
import { handleSyncRoute,isSyncRoute } from './api/sync-routes.mjs';
import { handleDeviceManagementRoute,isDeviceManagementRoute } from './api/device-routes.mjs';
import { handleBackupRoute,isBackupRoute } from './api/backup-routes.mjs';
import { handleReplicaRoute,isReplicaRoute } from './api/replica-routes.mjs';
import { resolveSession } from './auth/session.mjs';
import { resolveDeviceCredential } from './auth/device-credentials.mjs';
import { throttleIdentity,checkLoginThrottle,recordLoginFailure,clearLoginThrottle } from './auth/login-throttle.mjs';
import { checkSyncGeneration,decorateSyncResponse } from './sync/generation.mjs';
import { allowedOrigins,secureResponse,validateRequestOrigin } from './security/hardening.mjs';
import { writeCloudBackup } from './backup/r2-backup.mjs';
import { routeApi } from './api/router.mjs';
const JSON_HEADERS={'content-type':'application/json; charset=utf-8','cache-control':'no-store'};function json(body,status=200,headers={}){return new Response(JSON.stringify(body),{status,headers:{...JSON_HEADERS,...headers}});}async function authFor(request,env){return await resolveSession(request,env)||await resolveDeviceCredential(request,env);}
async function dispatch(request,env,ctx){const url=new URL(request.url);if(url.pathname===`${API_PREFIX}/health`){if(!['GET','HEAD'].includes(request.method))return json({ok:false,error:'method_not_allowed'},405,{allow:'GET, HEAD'});const body=publicHealth();return request.method==='HEAD'?new Response(null,{status:200,headers:JSON_HEADERS}):json(body);}if(url.pathname.startsWith(`${API_PREFIX}/`)&&!validateRequestOrigin(request,{allowedOrigins:allowedOrigins(env)}))return json({ok:false,error:'origin_forbidden'},403);if(url.pathname===`${API_PREFIX}/auth/login`){const identity=await throttleIdentity(request);if(identity){const gate=await checkLoginThrottle(env.DB,identity.keyHash);if(gate.blocked)return json({ok:false,error:'login_throttled',retryAfterSeconds:gate.retryAfterSeconds},429,{'retry-after':String(gate.retryAfterSeconds)});}const response=await handleAuthRoute(request,env,ctx,{auth:null});if(identity){if(response.status===200)await clearLoginThrottle(env.DB,identity.keyHash);else if(response.status===401)await recordLoginFailure(env.DB,identity.keyHash);}return response;}if(url.pathname.startsWith(`${API_PREFIX}/auth/`)){const auth=await authFor(request,env);return handleAuthRoute(request,env,ctx,{auth});}if(url.pathname.startsWith(`${API_PREFIX}/`)){const auth=await authFor(request,env);if(isDeviceManagementRoute(request))return handleDeviceManagementRoute(request,env,ctx,{auth});if(isBackupRoute(request))return handleBackupRoute(request,env,ctx,{auth});if(isReplicaRoute(request))return handleReplicaRoute(request,env,ctx,{auth});if(isAttachmentRoute(request))return handleAttachmentRoute(request,env,ctx,{auth});if(isRentalOperationRoute(request))return handleRentalRoute(request,env,ctx,{auth});if(isBillingOperationRoute(request))return handleBillingRoute(request,env,ctx,{auth});if(isInspectionOperationRoute(request))return handleInspectionRoute(request,env,ctx,{auth});if(isSyncRoute(request)){const generation=await checkSyncGeneration(request,env.DB,auth);if(!generation.ok)return json({ok:false,error:generation.error,restoreGeneration:generation.serverGeneration,clientGeneration:generation.clientGeneration},409);return decorateSyncResponse(await handleSyncRoute(request,env,ctx,{auth}),generation.serverGeneration);}return routeApi(request,env,ctx,{auth});}if(env?.ASSETS?.fetch)return env.ASSETS.fetch(request);return json({ok:false,error:'assets_unavailable'},503);}
export default{async fetch(request,env,ctx){return secureResponse(await dispatch(request,env,ctx));},async scheduled(_event,env,ctx){if(!env?.DB?.prepare||!env?.ATTACHMENTS?.put)return;const rows=await env.DB.prepare('SELECT id FROM installations WHERE deleted_at IS NULL ORDER BY id').all();for(const row of rows?.results??[])ctx.waitUntil(writeCloudBackup(env,row.id).catch(error=>console.error('scheduled backup failed',row.id,error?.message)));}};
