'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const {launchCloudPwa}=require('./fixtures/cloud-pwa.cjs');

async function selectByText(page,selector,text){const value=await page.locator(`${selector} option`).filter({hasText:text}).first().getAttribute('value');assert.ok(value,`Opção ${text} não encontrada em ${selector}`);await page.locator(selector).selectOption(value);}
async function selectFirstValue(page,selector){const value=await page.locator(`${selector} option`).nth(1).getAttribute('value');assert.ok(value,`Nenhuma opção disponível em ${selector}`);await page.locator(selector).selectOption(value);}
async function createBase(fx){
  const {page}=fx;
  await fx.openModule('customers');await page.locator('[data-customer-editor] summary').click();await page.locator('#cloud-customer-form').waitFor();await page.locator('#cloud-customer-form input[name="name"]').fill('Cliente Base');await page.locator('#cloud-customer-form button.primary').click();await page.getByText('Cliente salvo e sincronizado.').waitFor();
  await fx.openModule('vehicles');await page.locator('[data-vehicle-editor] summary').click();await page.locator('#cloud-vehicle-form').waitFor();await page.locator('#cloud-vehicle-form input[name="model"]').fill('Argo Base');await page.locator('#cloud-vehicle-form input[name="plate"]').fill('OFF1A23');await page.locator('#cloud-vehicle-form input[name="dailyRate"]').fill('100');await page.locator('#cloud-vehicle-form button.primary').click();await page.getByText('Veículo salvo e sincronizado.').waitFor();
  await fx.openModule('rentals');await page.locator('[data-rental-editor] > summary').click();await page.locator('#cloud-rental-form').waitFor();await selectByText(page,'#cloud-rental-form select[name="customerId"]','Cliente Base');await selectFirstValue(page,'#cloud-rental-form select[name="vehicleId"]');await page.locator('#cloud-rental-form input[name="pickupAt"]').fill('2026-10-10T10:00');await page.locator('#cloud-rental-form input[name="returnAt"]').fill('2026-10-12T10:00');await page.locator('#cloud-rental-form input[name="dailyRate"]').fill('100');await page.locator('#cloud-rental-form button').click();await page.getByText('Locação salva e sincronizada.').waitFor();
}

test('PWA offline sobrevive reload, preserva alteração+foto e sincroniza uma única vez ao reconectar',async t=>{
  const fx=await launchCloudPwa();t.after(()=>fx.close());const {page,context,db,installationId}=fx;await fx.login();await createBase(fx);const rentalId=db.sqlite.prepare('SELECT id FROM rentals WHERE installation_id=? LIMIT 1').get(installationId).id;
  await context.setOffline(true);
  await fx.openModule('customers');await page.locator('[data-customer-editor] summary').click();await page.locator('#cloud-customer-form input[name="name"]').fill('Cliente Offline');await page.locator('#cloud-customer-form input[name="phone"]').fill('16000000000');await page.locator('#cloud-customer-form button.primary').click();await page.getByText('Cliente salvo neste aparelho.').waitFor();
  await fx.openModule('rentals');await page.locator(`[data-rental-inspection="${rentalId}"]`).click();await page.locator('#cloud-inspection-form').waitFor();await page.locator('#cloud-inspection-form input[name="mileage"]').fill('15000');await page.locator('#cloud-inspection-form textarea[name="notes"]').fill('Criada totalmente offline');await page.locator('#cloud-inspection-form input[name="photo"]').setInputFiles({name:'offline.webp',mimeType:'image/webp',buffer:Buffer.from([82,73,70,70,12,0,0,0,87,69,66,80,1,2,3,4])});await page.locator('#cloud-inspection-form button').click();await page.getByText('Retirada salva neste aparelho. Será sincronizada quando houver conexão.').waitFor();assert.equal(await page.locator('#cloud-sync-state').textContent(),'Salvo neste aparelho');
  await page.reload({waitUntil:'domcontentloaded'});await page.locator('.mobile-appbar[for="cloud-mobile-menu"]').waitFor();await fx.openModule('customers');await page.getByText('Cliente Offline').waitFor();assert.equal(await page.locator('#cloud-sync-state').textContent(),'Salvo neste aparelho');
  assert.equal(db.scalar('SELECT COUNT(*) FROM customers WHERE installation_id=? AND name=?',installationId,'Cliente Offline'),0);assert.equal(db.scalar('SELECT COUNT(*) FROM attachments WHERE installation_id=?',installationId),0);
  await context.setOffline(false);await page.locator('#cloud-sync-state').waitFor({state:'attached'});await page.waitForFunction(()=>document.querySelector('#cloud-sync-state')?.textContent==='Sincronizado',null,{timeout:20000});
  assert.equal(db.scalar('SELECT COUNT(*) FROM customers WHERE installation_id=? AND name=?',installationId,'Cliente Offline'),1);assert.equal(db.scalar('SELECT COUNT(*) FROM inspections WHERE installation_id=? AND notes=?',installationId,'Criada totalmente offline'),1);assert.equal(db.scalar('SELECT COUNT(*) FROM attachments WHERE installation_id=? AND entity_type=?',installationId,'inspection'),1);assert.equal(fx.r2.objects.size,1);
  const before=db.scalar('SELECT COUNT(*) FROM sync_changes WHERE installation_id=?',installationId);await page.evaluate(()=>document.querySelector('#cloud-sync')?.click());await page.waitForTimeout(500);const after=db.scalar('SELECT COUNT(*) FROM sync_changes WHERE installation_id=?',installationId);assert.equal(after,before,'retry manual não pode duplicar operações já confirmadas');
});
