'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const {launchCloudPwa}=require('./fixtures/cloud-pwa.cjs');

async function selectByText(page,selector,text){const value=await page.locator(`${selector} option`).filter({hasText:text}).first().getAttribute('value');assert.ok(value,`Opção ${text} não encontrada em ${selector}`);await page.locator(selector).selectOption(value);}
async function selectFirstValue(page,selector){const value=await page.locator(`${selector} option`).nth(1).getAttribute('value');assert.ok(value,`Nenhuma opção disponível em ${selector}`);await page.locator(selector).selectOption(value);}

test('PWA mobile opera locação diária completa sem Electron/PC',async t=>{
  const fx=await launchCloudPwa();t.after(()=>fx.close());const {page,db,installationId}=fx;await fx.login();
  const shell=await page.locator('.cloud-shell').elementHandle();assert.ok(shell,'shell cloud não renderizado');
  await fx.openModule('customers');await page.locator('#cloud-customer-form').waitFor();assert.equal(await page.evaluate(node=>node===document.querySelector('.cloud-shell'),shell),true,'navegação não deve remontar o shell inteiro');await page.locator('#cloud-customer-form').waitFor();await page.locator('#cloud-customer-form input[name="name"]').fill('Cliente Mobile');await page.locator('#cloud-customer-form input[name="phone"]').fill('16999999999');await page.locator('#cloud-customer-form button').click();await page.getByText('Cliente salvo e sincronizado.').waitFor();
  await fx.openModule('vehicles');await page.locator('#cloud-vehicle-form').waitFor();await page.locator('#cloud-vehicle-form input[name="model"]').fill('Onix QA');await page.locator('#cloud-vehicle-form input[name="plate"]').fill('QAA1A23');await page.locator('#cloud-vehicle-form input[name="dailyRate"]').fill('80');await page.locator('#cloud-vehicle-form button').click();await page.getByText('Veículo salvo e sincronizado.').waitFor();
  await fx.openModule('rentals');await page.locator('#cloud-rental-form').waitFor();await selectByText(page,'#cloud-rental-form select[name="customerId"]','Cliente Mobile');await selectFirstValue(page,'#cloud-rental-form select[name="vehicleId"]');await page.locator('#cloud-rental-form input[name="pickupAt"]').fill('2026-10-01T10:00');await page.locator('#cloud-rental-form input[name="returnAt"]').fill('2026-10-04T10:00');await page.locator('#cloud-rental-form input[name="dailyRate"]').fill('80');await page.locator('#cloud-rental-form select[name="billingMode"]').selectOption('daily');await page.locator('#cloud-rental-form button').click();await page.getByText('Locação salva e sincronizada.').waitFor();
  const rentalId=db.sqlite.prepare('SELECT id FROM rentals WHERE installation_id=? ORDER BY created_at DESC LIMIT 1').get(installationId).id;assert.equal(db.scalar('SELECT COUNT(*) FROM billing_installments WHERE installation_id=? AND rental_id=?',installationId,rentalId),3);
  await fx.openModule('finance');const giveLow=page.locator(`[data-payment-rental="${rentalId}"]`);await giveLow.waitFor();await giveLow.click();await page.locator('[data-payment-form]').waitFor();await page.locator('[data-payment-form] button[type="submit"]').click();await page.getByText('Recebimento sincronizado.').waitFor();assert.equal(db.scalar('SELECT COUNT(*) FROM billing_payments WHERE installation_id=?',installationId),1);
  await fx.openModule('inspections');await page.locator('#cloud-inspection-form').waitFor();await page.locator('#cloud-inspection-form select[name="rentalId"]').selectOption(rentalId);await page.locator('#cloud-inspection-form input[name="mileage"]').fill('12345');await page.locator('#cloud-inspection-form select[name="fuelLevel"]').selectOption('3/4');await page.locator('#cloud-inspection-form textarea[name="notes"]').fill('Vistoria mobile QA');await page.locator('#cloud-inspection-form input[name="photo"]').setInputFiles({name:'vistoria.png',mimeType:'image/png',buffer:Buffer.from([137,80,78,71,13,10,26,10,1,2,3,4])});await page.locator('#cloud-inspection-form button').click();await page.getByText('Vistoria e evidência salvas.').waitFor();
  assert.equal(db.scalar('SELECT COUNT(*) FROM inspections WHERE installation_id=? AND rental_id=?',installationId,rentalId),1);assert.equal(db.scalar('SELECT COUNT(*) FROM attachments WHERE installation_id=? AND entity_type=?',installationId,'inspection'),1);assert.equal(fx.r2.objects.size,1);await page.waitForFunction(()=>document.querySelector('#cloud-sync-state')?.textContent==='Sincronizado');assert.equal(await page.locator('#cloud-sync-state').textContent(),'Sincronizado');
});
