'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {launchCloudPwa}=require('./fixtures/cloud-pwa.cjs');

const SCREEN_DIR=path.resolve(process.cwd(),'qa-artifacts','pwa-mobile');
async function snap(page,name){fs.mkdirSync(SCREEN_DIR,{recursive:true});await page.screenshot({path:path.join(SCREEN_DIR,name),fullPage:true});}
async function selectByText(page,selector,text){const value=await page.locator(`${selector} option`).filter({hasText:text}).first().getAttribute('value');assert.ok(value,`Opção ${text} não encontrada em ${selector}`);await page.locator(selector).selectOption(value);}
async function selectFirstValue(page,selector){const value=await page.locator(`${selector} option`).nth(1).getAttribute('value');assert.ok(value,`Nenhuma opção disponível em ${selector}`);await page.locator(selector).selectOption(value);}

test('PWA mobile opera locação diária completa sem Electron/PC',async t=>{
  const fx=await launchCloudPwa();t.after(()=>fx.close());const {page,db,installationId}=fx;await fx.login();await snap(page,'01-dashboard-pwa.png');
  await fx.openModule('customers');await page.locator('#cloud-customer-form').waitFor();await snap(page,'02-clientes-pwa.png');await page.locator('#cloud-customer-form input[name="name"]').fill('Cliente Mobile');await page.locator('#cloud-customer-form input[name="phone"]').fill('16999999999');await page.locator('#cloud-customer-form button').click();await page.getByText('Cliente salvo e sincronizado.').waitFor();
  await fx.openModule('vehicles');await page.locator('#cloud-vehicle-form').waitFor();await snap(page,'03-veiculos-pwa.png');await page.locator('#cloud-vehicle-form input[name="model"]').fill('Onix QA');await page.locator('#cloud-vehicle-form input[name="plate"]').fill('QAA1A23');await page.locator('#cloud-vehicle-form input[name="dailyRate"]').fill('80');await page.locator('#cloud-vehicle-form button').click();await page.getByText('Veículo salvo e sincronizado.').waitFor();
  await fx.openModule('rentals');await page.locator('#cloud-rental-form').waitFor();await selectByText(page,'#cloud-rental-form select[name="customerId"]','Cliente Mobile');await selectFirstValue(page,'#cloud-rental-form select[name="vehicleId"]');await page.locator('#cloud-rental-form input[name="pickupAt"]').fill('2026-10-01T10:00');await page.locator('#cloud-rental-form input[name="returnAt"]').fill('2026-10-04T10:00');await page.locator('#cloud-rental-form input[name="dailyRate"]').fill('80');await page.locator('#cloud-rental-form select[name="billingMode"]').selectOption('daily');await snap(page,'04-nova-locacao-pwa.png');await page.locator('#cloud-rental-form button').click();await page.getByText('Locação salva e sincronizada.').waitFor();
  const rentalId=db.sqlite.prepare('SELECT id FROM rentals WHERE installation_id=? ORDER BY created_at DESC LIMIT 1').get(installationId).id;assert.equal(db.scalar('SELECT COUNT(*) FROM billing_installments WHERE installation_id=? AND rental_id=?',installationId,rentalId),3);
  await fx.openModule('finance');const giveLow=page.locator(`[data-payment-rental="${rentalId}"]`);await giveLow.waitFor();await snap(page,'05-financeiro-contas-a-receber-pwa.png');await giveLow.click();await page.locator('[data-payment-form]').waitFor();await snap(page,'06-dar-baixa-pwa.png');await page.locator('[data-payment-form] button[type="submit"]').click();await page.getByText('Recebimento sincronizado.').waitFor();assert.equal(db.scalar('SELECT COUNT(*) FROM billing_payments WHERE installation_id=?',installationId),1);await snap(page,'07-recebimento-sincronizado-pwa.png');
  await fx.openModule('inspections');await page.locator('#cloud-inspection-form').waitFor();await page.locator('#cloud-inspection-form select[name="rentalId"]').selectOption(rentalId);await page.locator('#cloud-inspection-form input[name="mileage"]').fill('12345');await page.locator('#cloud-inspection-form select[name="fuelLevel"]').selectOption('3/4');await page.locator('#cloud-inspection-form textarea[name="notes"]').fill('Vistoria mobile QA');await page.locator('#cloud-inspection-form input[name="photo"]').setInputFiles({name:'vistoria.png',mimeType:'image/png',buffer:Buffer.from([137,80,78,71,13,10,26,10,1,2,3,4])});await snap(page,'08-vistoria-pwa.png');await page.locator('#cloud-inspection-form button').click();await page.getByText('Vistoria e evidência salvas.').waitFor();
  assert.equal(db.scalar('SELECT COUNT(*) FROM inspections WHERE installation_id=? AND rental_id=?',installationId,rentalId),1);assert.equal(db.scalar('SELECT COUNT(*) FROM attachments WHERE installation_id=? AND entity_type=?',installationId,'inspection'),1);assert.equal(fx.r2.objects.size,1);await page.waitForFunction(()=>document.querySelector('#cloud-sync-state')?.textContent==='Sincronizado');assert.equal(await page.locator('#cloud-sync-state').textContent(),'Sincronizado');await snap(page,'09-vistoria-salva-pwa.png');
});
