import { esc } from './common.mjs';

function when(value){if(!value)return'—';const date=new Date(value);return Number.isFinite(date.getTime())?date.toLocaleString('pt-BR'):String(value);}
function code(error){return String(error?.code??error?.message??'Não foi possível concluir a operação.');}
function auditRows(items=[]){return items.map(item=>`<tr><td>${esc(when(item.at))}</td><td>${esc(item.actorName||item.actorId||'Sistema')}</td><td><strong>${esc(item.action)}</strong></td><td>${esc(item.entityType||'—')}</td><td>${esc(item.entityId||'—')}</td><td><details><summary>Ver</summary><pre>${esc(JSON.stringify(item.details??{},null,2))}</pre></details></td></tr>`).join('')||'<tr><td colspan="6" class="empty">Nenhuma ação encontrada.</td></tr>';}
function backupRows(items=[]){return items.map(item=>`<tr><td><strong>${esc(item.id)}</strong></td><td><span class="badge">${esc(item.status)}</span></td><td>${esc(when(item.createdAt))}</td><td>${Number(item.restoreGeneration||0)}</td><td>${item.status==='valid'?`<button type="button" data-admin-restore="${esc(item.id)}">Restaurar</button>`:'—'}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">Nenhum backup cloud registrado.</td></tr>';}
function deviceRows(items=[]){return items.map(item=>`<tr><td><strong>${esc(item.name||item.id)}</strong><small>${esc(item.kind||'dispositivo')}</small></td><td>${item.active?'Ativo':'Revogado'}</td><td>${esc(when(item.lastSeenAt||item.sessionLastSeenAt))}</td><td>${Number(item.sessionCount||0)}</td><td>${item.active?`<button type="button" data-admin-device-revoke="${esc(item.id)}">Revogar</button>`:'—'}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">Nenhum dispositivo registrado.</td></tr>';}

export function administrationHtml(_snapshot,user){
  if(user?.role!=='admin')return'<section class="panel"><h1>Administração</h1><p>Esta área exige um administrador.</p></section>';
  return `<div data-test="admin-screen">
    <div class="page-head"><div><h1>Administração</h1><p>Auditoria, segurança, backups cloud e dados da empresa.</p></div><button type="button" class="secondary" id="admin-reload">Atualizar tudo</button></div>
    <p class="cloud-flash" data-admin-message hidden></p>
    <section class="panel" data-test="admin-settings"><h2>Empresa e configurações</h2><form id="admin-settings-form" class="form-grid"><label>Nome da empresa<input name="companyName" maxlength="160"></label><label>CPF/CNPJ<input name="document" maxlength="64"></label><label>Telefone<input name="phone" maxlength="64"></label><label>Endereço<input name="address" maxlength="500"></label><div class="full"><button class="primary">Salvar configurações</button> <small data-admin-settings-version></small></div></form></section>
    <section class="panel" data-test="admin-backups"><div class="heading"><div><small>RECUPERAÇÃO</small><h2>Backups cloud</h2></div><button type="button" class="primary" id="admin-backup-create">Gerar backup agora</button></div><p class="hint">D1 é exportado para objetos privados no R2. Somente backups com status válido podem ser restaurados.</p><div class="table-wrap"><table><thead><tr><th>ID</th><th>Status</th><th>Criado</th><th>Geração</th><th>Ação</th></tr></thead><tbody data-admin-backups-body><tr><td colspan="5">Carregando…</td></tr></tbody></table></div><form id="admin-restore-form" class="panel" data-test="admin-restore-form" hidden><h3>Restaurar backup</h3><p>Esta ação substitui os dados da nuvem, invalida as sessões atuais e exige novo login em todos os dispositivos.</p><input type="hidden" name="backupId"><div class="form-grid"><label>Backup<input name="backupLabel" readonly></label><label>Digite RESTAURAR<input name="confirmation" autocomplete="off" required></label><label class="full">Confirme sua senha de administrador<input name="password" type="password" autocomplete="current-password" required></label></div><div class="modal-actions"><button type="button" id="admin-restore-cancel">Cancelar</button><button class="primary">Confirmar restauração</button></div></form></section>
    <section class="panel" data-test="admin-devices"><div class="heading"><div><small>SESSÕES</small><h2>Dispositivos e sessões</h2></div><div class="actions"><button type="button" id="admin-revoke-others">Encerrar outras sessões</button><button type="button" id="admin-revoke-all">Encerrar todas</button></div></div><div class="table-wrap"><table><thead><tr><th>Dispositivo</th><th>Status</th><th>Último acesso</th><th>Sessões</th><th>Ação</th></tr></thead><tbody data-admin-devices-body><tr><td colspan="5">Carregando…</td></tr></tbody></table></div></section>
    <section class="panel" data-test="admin-audit"><div class="heading"><div><small>HISTÓRICO</small><h2>Auditoria</h2></div></div><form id="admin-audit-filter" class="form-grid"><label>Ação<input name="action" placeholder="Ex.: settings.update"></label><label>Entidade<input name="entityType" placeholder="Ex.: customer"></label><label>De<input name="from" type="date"></label><label>Até<input name="to" type="date"></label><div class="full"><button class="secondary">Filtrar</button> <button type="button" id="admin-audit-clear">Limpar</button></div></form><div class="table-wrap"><table><thead><tr><th>Data</th><th>Usuário</th><th>Ação</th><th>Entidade</th><th>ID</th><th>Detalhes</th></tr></thead><tbody data-admin-audit-body><tr><td colspan="6">Carregando…</td></tr></tbody></table></div><div class="actions"><button type="button" id="admin-audit-prev">Anterior</button><span data-admin-audit-page></span><button type="button" id="admin-audit-next">Próxima</button></div></section>
  </div>`;
}

export function bindAdministration(root,{actions,user}){
  if(!root||user?.role!=='admin')return;
  const messageNode=root.querySelector('[data-admin-message]'),settingsForm=root.querySelector('#admin-settings-form'),backupsBody=root.querySelector('[data-admin-backups-body]'),devicesBody=root.querySelector('[data-admin-devices-body]'),auditBody=root.querySelector('[data-admin-audit-body]'),pageNode=root.querySelector('[data-admin-audit-page]'),restoreForm=root.querySelector('#admin-restore-form');
  let settingsVersion=0,auditFilters={limit:25,offset:0},auditPage={total:0,limit:25,offset:0,nextOffset:null};
  function message(text,{error=false}={}){messageNode.hidden=!text;messageNode.textContent=text||'';messageNode.classList.toggle('error',error);}
  function setBusy(button,busy){if(button)button.disabled=Boolean(busy);}
  function fillSettings(result){const settings=result?.settings??{};settingsVersion=Number(result?.version)||0;for(const name of ['companyName','document','phone','address']){const input=settingsForm.elements.namedItem(name);if(input)input.value=String(settings[name]??'');}const label=root.querySelector('[data-admin-settings-version]');if(label)label.textContent=`Versão ${settingsVersion}`;}
  function bindRestoreButtons(){for(const button of root.querySelectorAll('[data-admin-restore]'))button.onclick=()=>{const id=button.dataset.adminRestore;restoreForm.hidden=false;restoreForm.elements.backupId.value=id;restoreForm.elements.backupLabel.value=id;restoreForm.elements.confirmation.value='';restoreForm.elements.password.value='';restoreForm.scrollIntoView({behavior:'smooth',block:'center'});};}
  function bindDeviceButtons(){for(const button of root.querySelectorAll('[data-admin-device-revoke]'))button.onclick=async()=>{const id=button.dataset.adminDeviceRevoke;if(!confirm(`Revogar o dispositivo ${id}? As sessões e credenciais dele serão invalidadas.`))return;setBusy(button,true);try{await actions.revokeDevice(id);message('Dispositivo revogado.');await loadDevices();}catch(error){message(code(error),{error:true});}finally{setBusy(button,false);}};}
  async function loadSettings(){fillSettings(await actions.getAdminSettings());}
  async function loadBackups(){const items=await actions.listCloudBackups();backupsBody.innerHTML=backupRows(items);bindRestoreButtons();}
  async function loadDevices(){const items=await actions.listDevices();devicesBody.innerHTML=deviceRows(items);bindDeviceButtons();}
  async function loadAudit(){const result=await actions.getAdminAudit(auditFilters);auditPage=result?.pagination??auditPage;auditBody.innerHTML=auditRows(result?.items??[]);const first=auditPage.total?auditPage.offset+1:0,last=Math.min(auditPage.total,auditPage.offset+auditPage.limit);pageNode.textContent=`${first}–${last} de ${auditPage.total}`;root.querySelector('#admin-audit-prev').disabled=auditPage.offset<=0;root.querySelector('#admin-audit-next').disabled=auditPage.nextOffset==null;}
  async function loadAll(){message('Carregando administração…');try{await Promise.all([loadSettings(),loadBackups(),loadDevices(),loadAudit()]);message('Administração atualizada.');}catch(error){message(code(error),{error:true});}}
  settingsForm.onsubmit=async event=>{event.preventDefault();const button=settingsForm.querySelector('button[type="submit"]'),fd=new FormData(settingsForm),data={companyName:String(fd.get('companyName')??''),document:String(fd.get('document')??''),phone:String(fd.get('phone')??''),address:String(fd.get('address')??'')};setBusy(button,true);try{const result=await actions.updateAdminSettings(data,settingsVersion);fillSettings(result);message('Configurações salvas.');await loadAudit();}catch(error){message(code(error),{error:true});if(error?.status===409)await loadSettings().catch(()=>{});}finally{setBusy(button,false);}};
  root.querySelector('#admin-backup-create').onclick=async event=>{const button=event.currentTarget;setBusy(button,true);try{message('Gerando e verificando backup cloud…');await actions.createCloudBackup();await loadBackups();message('Backup cloud concluído.');}catch(error){message(code(error),{error:true});}finally{setBusy(button,false);}};
  root.querySelector('#admin-restore-cancel').onclick=()=>{restoreForm.hidden=true;restoreForm.reset();};
  restoreForm.onsubmit=async event=>{event.preventDefault();const fd=new FormData(restoreForm),id=String(fd.get('backupId')??''),confirmation=String(fd.get('confirmation')??'').trim(),password=String(fd.get('password')??''),button=restoreForm.querySelector('button[type="submit"]');if(confirmation!=='RESTAURAR'){message('Digite exatamente RESTAURAR para confirmar.',{error:true});return;}if(!password){message('Informe sua senha de administrador.',{error:true});return;}if(!confirm(`Restaurar o backup ${id}? Todos os dispositivos precisarão entrar novamente.`))return;setBusy(button,true);try{message('Validando backup e restaurando…');await actions.restoreCloudBackup(id,password);}catch(error){message(code(error),{error:true});setBusy(button,false);}};
  root.querySelector('#admin-revoke-others').onclick=async event=>{if(!confirm('Encerrar todas as outras sessões desta conta?'))return;const button=event.currentTarget;setBusy(button,true);try{const result=await actions.revokeOtherSessions();message(`${Number(result?.revoked||0)} sessão(ões) encerrada(s).`);await loadDevices();}catch(error){message(code(error),{error:true});}finally{setBusy(button,false);}};
  root.querySelector('#admin-revoke-all').onclick=async event=>{if(!confirm('Encerrar TODAS as sessões, inclusive esta? Será necessário entrar novamente.'))return;const button=event.currentTarget;setBusy(button,true);try{await actions.revokeAllSessions();}catch(error){message(code(error),{error:true});setBusy(button,false);}};
  root.querySelector('#admin-audit-filter').onsubmit=async event=>{event.preventDefault();const fd=new FormData(event.currentTarget),from=String(fd.get('from')??''),to=String(fd.get('to')??'');auditFilters={action:String(fd.get('action')??'').trim(),entityType:String(fd.get('entityType')??'').trim(),from:from?`${from}T00:00:00.000Z`:'',to:to?`${to}T23:59:59.999Z`:'',limit:25,offset:0};try{await loadAudit();}catch(error){message(code(error),{error:true});}};
  root.querySelector('#admin-audit-clear').onclick=()=>{root.querySelector('#admin-audit-filter').reset();auditFilters={limit:25,offset:0};void loadAudit().catch(error=>message(code(error),{error:true}));};
  root.querySelector('#admin-audit-prev').onclick=()=>{auditFilters.offset=Math.max(0,(auditPage.offset||0)-(auditPage.limit||25));void loadAudit().catch(error=>message(code(error),{error:true}));};
  root.querySelector('#admin-audit-next').onclick=()=>{if(auditPage.nextOffset==null)return;auditFilters.offset=auditPage.nextOffset;void loadAudit().catch(error=>message(code(error),{error:true}));};
  root.querySelector('#admin-reload').onclick=()=>void loadAll();
  void loadAll();
}
