import { can } from '../../domain/auth.mjs';
import { buildOperationalAlerts } from '../../domain/alerts.mjs';
import { alertKindLabel,emptyStateHtml,esc,shortDate,statusLabel } from './common.mjs';

export function alertsHtml(snapshot,user){const alerts=buildOperationalAlerts(snapshot),writable=can(user,'alerts.write');return `<div class="heading"><div><small>PRAZOS E RISCOS</small><h1>Alertas</h1></div><span class="badge">${alerts.length} ativos</span></div><div class="cloud-card-list">${alerts.map(a=>`<article class="card cloud-entity-card ${esc(a.severity||'')}"><div><strong>${esc(a.title)}</strong><small>${esc(alertKindLabel(a.kind))} · ${a.dueAt?shortDate(a.dueAt):'sem vencimento'} · ${esc(statusLabel(a.status||'active'))}</small><small>${esc(a.description||a.message||'')}</small></div>${writable?`<div class="actions">${a.status!=='acknowledged'?`<button data-alert-ack="${esc(a.id)}">Reconhecer</button>`:''}<button data-alert-dismiss="${esc(a.id)}">Resolver</button></div>`:''}</article>`).join('')||emptyStateHtml({title:'Nenhum alerta no momento',description:'Prazos de locações, manutenção e documentos estão sem pendências que exijam ação.'})}</div>`;}
function openAlertResolutionDialog(){
  return new Promise(resolve=>{
    const host=document.createElement('div');
    host.innerHTML=`<div class="modal-overlay" data-alert-overlay><form class="modal" data-alert-form><div class="modal-head"><div><small>ALERTA</small><h2>Resolver pendência</h2></div><button type="button" aria-label="Fechar" data-cancel>×</button></div><label>Motivo / resolução<textarea name="reason" required>Resolvido</textarea></label><div class="modal-actions"><button type="button" data-cancel>Cancelar</button><button class="primary">Confirmar resolução</button></div></form></div>`;
    const overlay=host.firstElementChild,form=overlay.querySelector('[data-alert-form]');document.body.append(overlay);const close=value=>{overlay.remove();resolve(value);};overlay.querySelectorAll('[data-cancel]').forEach(button=>button.onclick=()=>close(null));overlay.onclick=event=>{if(event.target===overlay)close(null);};form.onsubmit=event=>{event.preventDefault();const value=String(new FormData(form).get('reason')||'').trim();if(value)close(value);};form.elements.reason.focus();form.elements.reason.select();
  });
}
export function bindAlerts(root,{user,actions}){if(!can(user,'alerts.write'))return;root.querySelectorAll('[data-alert-ack]').forEach(button=>button.onclick=async()=>{await actions.queue('alert.acknowledge',{alertId:button.dataset.alertAck},'ALT');await actions.refresh('alerts');});root.querySelectorAll('[data-alert-dismiss]').forEach(button=>button.onclick=async()=>{const reason=await openAlertResolutionDialog();if(!reason)return;await actions.queue('alert.dismiss',{alertId:button.dataset.alertDismiss,reason},'ALT');await actions.refresh('alerts');});}
