import { can } from '../../domain/auth.mjs';
import { billingPurposeLabel,brDateToIso,emptyStateHtml,esc,frequencyLabel,money,shortDate } from './common.mjs';
import { collectInstallmentPayment } from './payment-flow.mjs';

function balance(item){return Math.max(0,Number(item.amount||0)-Number(item.paidAmount||0));}
function paymentStatus(status){return({open:'Em aberto',partial:'Parcial',paid:'Pago',cancelled:'Cancelado',overdue:'Vencido'})[status]??String(status||'').replaceAll('_',' ');}
function rentalFor(snapshot,id){return (snapshot.rentals??[]).find(item=>String(item.id)===String(id))??null;}
function customerForInstallment(snapshot,item){const rental=rentalFor(snapshot,item.rentalId),customerId=item.customerId??rental?.customerId;return (snapshot.customers??[]).find(customer=>String(customer.id)===String(customerId))??null;}
function vehicleForRental(snapshot,rental){return (snapshot.vehicles??[]).find(vehicle=>String(vehicle.id)===String(rental?.vehicleId))??null;}
function dueSort(a,b){return String(a.dueAt||'9999-12-31').localeCompare(String(b.dueAt||'9999-12-31'))||Number(a.sequence||0)-Number(b.sequence||0);}

function installmentsHtml(snapshot,user){
  const writable=can(user,'billing.write'),groups=new Map();
  for(const item of snapshot.billingInstallments??[]){
    const rental=rentalFor(snapshot,item.rentalId),customer=customerForInstallment(snapshot,item),customerId=String(customer?.id??item.customerId??rental?.customerId??'SEM-CLIENTE'),rentalId=String(rental?.id??item.rentalId??'SEM-LOCACAO');
    if(!groups.has(customerId))groups.set(customerId,{customerId,customer,rows:new Map()});
    const group=groups.get(customerId);if(!group.rows.has(rentalId))group.rows.set(rentalId,{rentalId,rental,items:[]});group.rows.get(rentalId).items.push(item);
  }
  const ordered=[...groups.values()].sort((a,b)=>String(a.customer?.name??a.customerId).localeCompare(String(b.customer?.name??b.customerId),'pt-BR'));
  return ordered.map(group=>{
    const rentals=[...group.rows.values()].sort((a,b)=>String(a.rental?.pickupAt??'').localeCompare(String(b.rental?.pickupAt??''))||a.rentalId.localeCompare(b.rentalId));
    const all=rentals.flatMap(row=>row.items),openItems=all.filter(item=>balance(item)>0&&item.status!=='cancelled'),totalOpen=openItems.reduce((sum,item)=>sum+balance(item),0);
    const rentalBlocks=rentals.map(row=>{
      const rental=row.rental,vehicle=vehicleForRental(snapshot,rental),items=[...row.items].sort(dueSort),open=items.filter(item=>balance(item)>0&&item.status!=='cancelled'),rentalOpen=open.reduce((sum,item)=>sum+balance(item),0),vehicleLabel=vehicle?[vehicle.model,vehicle.plate].filter(Boolean).join(' · '):`Locação ${row.rentalId.slice(0,12)}`;
      const cards=items.map(item=>{const openValue=balance(item),daily=rental?.billingMode==='daily'&&Number(item.sequence||0)>0;return `<article class="billing-installment"><div class="billing-installment-main"><div><small>${daily?`DIÁRIA #${Number(item.sequence)}`:'VENCIMENTO'}</small><strong>${shortDate(item.dueAt)}</strong></div><div><small>VALOR</small><strong>${money(item.amount)}</strong></div><div><small>RECEBIDO</small><strong>${money(item.paidAmount)}</strong></div><span class="billing-status billing-status-${esc(item.status||'open')}">${esc(paymentStatus(item.status))}</span></div>${openValue>0?`<div class="billing-installment-footer"><span>Saldo <strong>${money(openValue)}</strong></span>${writable&&item.status!=='cancelled'?`<button class="primary" data-installment-pay="${esc(item.id)}">Dar baixa</button>`:''}</div>`:''}</article>`}).join('');
      return `<section class="billing-rental" data-billing-rental="${esc(row.rentalId)}"><div class="billing-rental-head"><div><small>LOCAÇÃO</small><strong>${esc(vehicleLabel)}</strong>${rental?`<span>${rental.periodMode==='continuous'?'Contínua':`${shortDate(rental.pickupAt)} → ${shortDate(rental.returnAt)}`}</span>`:''}</div><div class="billing-rental-summary"><strong>${open.length} ${open.length===1?'parcela em aberto':'parcelas em aberto'}</strong><span>Saldo ${money(rentalOpen)}</span></div></div><div class="billing-installments">${cards}</div></section>`;
    }).join('');
    return `<article class="billing-customer" data-billing-customer="${esc(group.customerId)}"><header class="billing-customer-head"><div><small>CLIENTE</small><h3>${esc(group.customer?.name??group.customerId)}</h3></div><div class="billing-customer-summary"><strong>${openItems.length} ${openItems.length===1?'parcela em aberto':'parcelas em aberto'}</strong><span>Saldo total ${money(totalOpen)}</span></div></header>${rentalBlocks}</article>`;
  }).join('');
}

export function billingHtml(snapshot,user){
  const writable=can(user,'billing.write'),plans=(snapshot.billingPlans??[]).map(p=>`<article class="card"><strong>${esc(billingPurposeLabel(p.purpose))} · ${money(p.amount)}</strong><small>${esc(frequencyLabel(p.frequency))} · ${Number(p.occurrences||0)} ocorrência(s) · início ${shortDate(p.firstDueAt)} · ${p.active?'ativa':'inativa'}</small></article>`).join(''),installments=installmentsHtml(snapshot,user);
  return `<div class="heading"><div><small>PLANOS E PARCELAS</small><h1>Cobranças</h1></div></div><section class="panel billing-panel"><div class="panel-title"><div><h2>Parcelas por cliente</h2><span>Organizadas por locação e vencimento</span></div></div><div class="billing-customer-list">${installments||emptyStateHtml({title:'Nenhuma parcela gerada',description:'As parcelas aparecerão aqui quando houver uma locação com cobrança por diária ou um plano de cobrança.',actionLabel:writable&&snapshot.rentals.length?'Criar plano de cobrança':'',action:writable&&snapshot.rentals.length?'billing-plan-create':''})}</div></section>${writable?`<details class="panel cloud-create-panel"><summary>+ Criar plano de cobrança</summary><form id="cloud-billing-plan-form" class="cloud-form cloud-inline-form"><label>Locação<select name="rentalId" required><option value="">Selecione</option>${snapshot.rentals.map(r=>`<option value="${esc(r.id)}">${esc(r.id.slice(0,12))} · ${money(r.total)}</option>`).join('')}</select></label><label>Frequência<select name="frequency"><option value="monthly">Mensal</option><option value="weekly">Semanal</option><option value="daily">Diária</option><option value="custom">Personalizada</option></select></label><label>Dias personalizados<input name="customDays" type="number" min="1" value="30"></label><label>Valor<input name="amount" type="number" min="0.01" step="0.01" required></label><label>Ocorrências<input name="occurrences" type="number" min="1" max="120" value="1" required></label><label>Primeiro vencimento<input name="firstDueAt" inputmode="numeric" placeholder="dd/mm/aaaa" required></label><label>Multa %<input name="finePercent" type="number" min="0" step="0.01" value="0"></label><label>Juros ao mês %<input name="interestMonthlyPercent" type="number" min="0" step="0.01" value="0"></label><button class="primary full">Criar plano</button></form></details>`:''}<section class="panel"><div class="panel-title"><div><h2>Planos</h2><span>${snapshot.billingPlans.length} plano(s)</span></div></div><div class="cloud-card-list">${plans||emptyStateHtml({title:'Nenhum plano de cobrança',description:snapshot.rentals.length?'Crie um plano para organizar vencimentos, multa e juros desta locação.':'Crie uma locação antes de cadastrar um plano de cobrança.',actionLabel:writable&&snapshot.rentals.length?'Criar plano':'',action:writable&&snapshot.rentals.length?'billing-plan-create':''})}</div></section>`;
}

export function bindBilling(root,{snapshot,user,actions}){const form=root.querySelector('#cloud-billing-plan-form');for(const button of root.querySelectorAll('[data-empty-action="billing-plan-create"]'))button.onclick=()=>{const editor=form?.closest('details');if(editor)editor.open=true;form?.elements.rentalId?.focus();form?.scrollIntoView({behavior:'smooth',block:'start'});};if(!can(user,'billing.write'))return;if(form)form.onsubmit=async event=>{event.preventDefault();const fd=new FormData(form);await actions.queue('billing.plan.create',{id:`COB-${crypto.randomUUID()}`,rentalId:String(fd.get('rentalId')),frequency:String(fd.get('frequency')),customDays:Number(fd.get('customDays')||0),amount:Number(fd.get('amount')),occurrences:Number(fd.get('occurrences')),firstDueAt:brDateToIso(fd.get('firstDueAt'),{required:true}),finePercent:Number(fd.get('finePercent')||0),interestMonthlyPercent:Number(fd.get('interestMonthlyPercent')||0)},'BILL');await actions.refresh('billing');};root.querySelectorAll('[data-installment-pay]').forEach(button=>button.onclick=()=>collectInstallmentPayment(snapshot,button.dataset.installmentPay,actions,{refresh:'billing'}));}
