import { can } from '../../domain/auth.mjs';
import { delinquencySummary } from '../../domain/commercial.mjs';
import { brDateToIso,emptyStateHtml,esc,money,shortDate } from './common.mjs';

export function delinquencyHtml(snapshot,user,asOf=new Date()){const when=asOf instanceof Date?asOf.toISOString():String(asOf),summary=delinquencySummary(snapshot,when),writable=can(user,'billing.write'),rows=summary.rows.map(({item,balance})=>{const customer=snapshot.customers.find(c=>c.id===item.customerId),actions=(snapshot.collectionActions??[]).filter(a=>a.installmentId===item.id);return `<article class="card cloud-entity-card"><div><strong>${esc(customer?.name||item.customerId)} · ${money(balance.totalDue)}</strong><small>Venceu ${shortDate(item.dueAt)} · ${balance.daysLate} dias em atraso · multa ${money(balance.fine)} · juros ${money(balance.interest)}</small><small>${actions.length} contato(s) registrado(s)${actions[0]?` · último: ${esc(actions[0].channel)} ${shortDate(actions[0].createdAt)}`:''}</small></div>${writable?`<div class="actions"><button data-collection-action="${esc(item.id)}">Registrar cobrança</button></div>`:''}</article>`}).join('');return `<div class="heading"><div><small>ATRASOS E COBRANÇA</small><h1>Inadimplência</h1></div></div><div class="cards six"><article><small>Total vencido</small><strong>${money(summary.total)}</strong></article><article><small>Parcelas</small><strong>${summary.count}</strong></article><article><small>Clientes</small><strong>${summary.customers}</strong></article><article><small>Média de atraso</small><strong>${summary.averageDaysLate} dias</strong></article><article><small>Vence hoje</small><strong>${money(summary.dueToday)}</strong></article><article><small>Próximos 7 dias</small><strong>${money(summary.dueNext7Days)}</strong></article></div><section class="panel"><h2>Faixas de atraso</h2><div class="kpi-lines">${Object.entries(summary.aging).map(([label,value])=>`<p><span>${label} dias</span><b>${money(value)}</b></p>`).join('')}</div></section><section class="panel"><h2>Clientes em atraso</h2><div class="cloud-card-list">${rows||emptyStateHtml({title:'Nenhuma parcela vencida',description:'Não há clientes com cobrança em atraso nesta data.'})}</div></section>`;}

function openCollectionDialog(){
  return new Promise(resolve=>{
    const host=document.createElement('div');
    host.innerHTML=`<div class="modal-overlay" data-collection-overlay><form class="modal" data-collection-form><div class="modal-head"><div><small>COBRANÇA</small><h2>Registrar contato</h2></div><button type="button" aria-label="Fechar" data-cancel>×</button></div><div class="form-grid"><label class="full">Observação<textarea name="note" required></textarea></label><label>Canal<select name="channel"><option>WhatsApp</option><option>Telefone</option><option>E-mail</option><option>Outro</option></select></label><label>Promessa de pagamento<input name="promiseAt" inputmode="numeric" placeholder="dd/mm/aaaa"></label><label>Próxima ação<input name="nextActionAt" inputmode="numeric" placeholder="dd/mm/aaaa"></label></div><div class="modal-actions"><button type="button" data-cancel>Cancelar</button><button class="primary">Salvar contato</button></div></form></div>`;
    const overlay=host.firstElementChild,form=overlay.querySelector('[data-collection-form]');document.body.append(overlay);const close=value=>{overlay.remove();resolve(value);};overlay.querySelectorAll('[data-cancel]').forEach(button=>button.onclick=()=>close(null));overlay.onclick=event=>{if(event.target===overlay)close(null);};
    form.onsubmit=event=>{event.preventDefault();const fd=new FormData(form);try{close({note:String(fd.get('note')||'').trim(),channel:String(fd.get('channel')||'Outro'),promiseAt:fd.get('promiseAt')?brDateToIso(fd.get('promiseAt')):null,nextActionAt:fd.get('nextActionAt')?brDateToIso(fd.get('nextActionAt')):null});}catch(error){form.querySelector('input[name="promiseAt"]').setCustomValidity(error.message);form.querySelector('input[name="promiseAt"]').reportValidity();form.querySelector('input[name="promiseAt"]').setCustomValidity('');}};form.elements.note.focus();
  });
}
export function bindDelinquency(root,{user,actions}){if(!can(user,'billing.write'))return;root.querySelectorAll('[data-collection-action]').forEach(button=>button.onclick=async()=>{const input=await openCollectionDialog();if(!input)return;await actions.queue('collectionAction.create',{id:`COL-${crypto.randomUUID()}`,installmentId:button.dataset.collectionAction,...input},'COL');await actions.refresh('delinquency');});}
