import { can } from '../../domain/auth.mjs';
import { DEFAULT_INSPECTION_ITEMS } from '../../domain/inspection.mjs';
import { esc,shortDate } from './common.mjs';

function optionRentals(snapshot,kind){return snapshot.rentals.filter(r=>kind==='pickup'?['reserva','retirada'].includes(r.status):['em_uso','devolucao'].includes(r.status)).map(r=>{const v=snapshot.vehicles.find(x=>x.id===r.vehicleId),c=snapshot.customers.find(x=>x.id===r.customerId);return `<option value="${esc(r.id)}">${esc(v?.plate||r.vehicleId)} · ${esc(c?.name||r.customerId)}</option>`}).join('');}
export function inspectionsHtml(snapshot,user){const writable=can(user,'inspection.write');const cards=(snapshot.inspections??[]).map(i=>{const rental=snapshot.rentals.find(r=>r.id===i.rentalId),vehicle=snapshot.vehicles.find(v=>v.id===(i.vehicleId||rental?.vehicleId));const completed=(i.checklist??[]).filter(x=>x.done).length,total=(i.checklist??[]).length;const photos=(snapshot.attachments??[]).filter(a=>a.entityType==='inspection'&&a.entityId===i.id);return `<article class="card cloud-entity-card"><div><strong>${i.kind==='return'?'Devolução':'Retirada'} · ${esc(vehicle?.plate||i.vehicleId||'-')}</strong><small>${esc(i.status)} · ${completed}/${total||DEFAULT_INSPECTION_ITEMS.length} itens · ${photos.length} foto(s)</small><small>${Number(i.mileage||0).toLocaleString('pt-BR')} km · combustível ${esc(i.fuelLevel||'-')} · ${shortDate(i.completedAt)}</small><small>${esc((i.damages??[]).join(', ')||'Sem avarias registradas')}</small></div><div class="actions"><button data-inspection-pdf="${esc(i.id)}">PDF</button></div></article>`}).join('');return `<div class="heading"><div><small>CHECKLIST, FOTOS E AVARIAS</small><h1>Vistorias</h1></div></div><div class="cloud-grid">${writable?`<form id="cloud-inspection-form" class="panel cloud-form cloud-form-sections" data-test="inspection-form"><h2>Nova vistoria</h2><fieldset><legend>Locação</legend><label>Tipo<select name="kind"><option value="pickup">Retirada</option><option value="return">Devolução</option></select></label><label>Locação<select name="rentalId" required><option value="">Selecione</option>${optionRentals(snapshot,'pickup')}</select></label></fieldset><fieldset><legend>Checklist</legend><div class="full checklist-grid" data-test="inspection-checklist">${DEFAULT_INSPECTION_ITEMS.map(([id,label])=>`<label class="checkline"><input type="checkbox" name="check-${esc(id)}" checked required> ${esc(label)}</label>`).join('')}</div></fieldset><fieldset><legend>Condição do veículo</legend><label>Quilometragem<input name="mileage" type="number" min="0" required></label><label>Combustível<select name="fuelLevel" required><option>Reserva</option><option>1/4</option><option>1/2</option><option selected>3/4</option><option>Cheio</option></select></label><label class="full">Fotos<input name="photo" type="file" accept="image/jpeg,image/png,image/webp" capture="environment" multiple required></label></fieldset><fieldset><legend>Avarias e observações</legend><label class="full">Avarias (uma por linha)<textarea name="damages"></textarea></label><label class="full">Observações<textarea name="notes"></textarea></label></fieldset><button class="primary full">Concluir vistoria</button></form>`:''}<section class="panel"><h2>Histórico</h2><div class="cloud-card-list">${cards||'<div class="empty">Nenhuma vistoria.</div>'}</div></section></div>`;}

export function bindInspections(root,{snapshot,user,actions}){const form=root.querySelector('#cloud-inspection-form');if(form){const kind=form.elements.kind,rental=form.elements.rentalId;kind.onchange=()=>{rental.innerHTML=`<option value="">Selecione</option>${optionRentals(snapshot,kind.value)}`;};form.onsubmit=async event=>{event.preventDefault();const files=[...form.elements.photo.files];if(!files.length)throw new Error('Inclua pelo menos uma foto.');const fd=new FormData(form),inspectionId=`VIS-${crypto.randomUUID()}`,items=DEFAULT_INSPECTION_ITEMS.map(([key,label])=>({key,label,done:Boolean(form.elements[`check-${key}`].checked),evidence:key==='photos'?`${files.length} foto(s)`:null}));if(items.some(item=>!item.done))throw new Error('Conclua todos os itens do checklist.');const payload={id:inspectionId,rentalId:String(fd.get('rentalId')),kind:String(fd.get('kind')),mileage:Number(fd.get('mileage')),fuelLevel:String(fd.get('fuelLevel')),notes:String(fd.get('notes')||''),damages:String(fd.get('damages')||'').split('\n').map(x=>x.trim()).filter(Boolean),items};await actions.queue('inspection.create',payload,'VIS');for(const file of files)await actions.uploadFile(file,'inspection',inspectionId);await actions.flush();await actions.refresh('inspections');};}
  root.querySelectorAll('[data-inspection-pdf]').forEach(button=>button.onclick=()=>actions.downloadInspectionPdf(button.dataset.inspectionPdf,snapshot));
}
