import { can } from '../../domain/auth.mjs';
import { brDateToIso,emptyStateHtml,esc,money,pageControls,shortDate,statusLabel } from './common.mjs';

export function maintenanceHtml(snapshot,user,{pagination={}}={}){const writable=can(user,'maintenance.write'),rows=(snapshot.maintenance??[]).map(m=>{const vehicle=snapshot.vehicles.find(v=>v.id===m.vehicleId);return `<article class="card cloud-entity-card"><div><strong>${esc(vehicle?.model||m.vehicleId)} · ${esc(m.type)}</strong><small>${esc(statusLabel(m.status))} · limite ${shortDate(m.dueAt)}${m.dueMileage?` · ${Number(m.dueMileage).toLocaleString('pt-BR')} km`:''}</small><small>Estimado ${money(m.costEstimate)}${m.status==='completed'?` · realizado ${money(m.cost)}`:''} · ${esc(m.notes||'')}</small></div>${writable?`<div class="actions">${m.status==='scheduled'?`<button data-maintenance-start="${esc(m.id)}">Iniciar</button>`:''}${m.status==='in_progress'?`<button data-maintenance-complete="${esc(m.id)}">Concluir</button>`:''}</div>`:''}</article>`}).join('');return `<div class="heading"><div><small>FROTA PREVENTIVA</small><h1>Manutenção</h1></div></div>${writable?`<details class="panel cloud-create-panel"><summary>+ Agendar manutenção</summary><form id="cloud-maintenance-form" class="cloud-form cloud-inline-form"><label>Veículo<select name="vehicleId" required><option value="">Selecione</option>${snapshot.vehicles.map(v=>`<option value="${esc(v.id)}">${esc(v.model)} · ${esc(v.plate)}</option>`).join('')}</select></label><label>Serviço<input name="type" required></label><label>Data limite<input name="dueAt" inputmode="numeric" placeholder="dd/mm/aaaa"></label><label>KM limite<input name="dueMileage" type="number" min="0"></label><label>Custo estimado<input name="costEstimate" type="number" min="0" step="0.01"></label><label class="full">Observações<textarea name="notes"></textarea></label><button class="primary full">Agendar</button></form></details>`:''}<section class="panel"><div class="panel-title"><div><h2>Histórico e agenda</h2><span>${snapshot.maintenance.length} registro(s)</span></div></div>${pageControls('maintenance',pagination.maintenance??{},{search:true,placeholder:'Serviço, status ou observação'})}<div class="cloud-card-list">${rows||emptyStateHtml({title:String(pagination.maintenance?.q||'').trim()?'Nenhuma manutenção encontrada':'Nenhuma manutenção registrada',description:String(pagination.maintenance?.q||'').trim()?'Ajuste a busca para encontrar outro registro.':snapshot.vehicles.length?'Agende a primeira manutenção para acompanhar prazos, quilometragem e custos da frota.':'Cadastre um veículo antes de agendar a primeira manutenção.',actionLabel:writable&&snapshot.vehicles.length?'Agendar manutenção':'',action:writable&&snapshot.vehicles.length?'maintenance-create':''})}</div></section>`;}
function openMaintenanceCompleteDialog(){
  return new Promise(resolve=>{
    const host=document.createElement('div');
    host.innerHTML=`<div class="modal-overlay" data-maintenance-overlay><form class="modal" data-maintenance-complete-form><div class="modal-head"><div><small>MANUTENÇÃO</small><h2>Concluir serviço</h2></div><button type="button" aria-label="Fechar" data-cancel>×</button></div><div class="form-grid"><label>Custo realizado<input name="cost" type="number" min="0" step="0.01" value="0" required></label><label>Quilometragem atual<input name="mileage" type="number" min="0"></label><label class="full">Observações<textarea name="notes"></textarea></label></div><div class="modal-actions"><button type="button" data-cancel>Cancelar</button><button class="primary">Concluir manutenção</button></div></form></div>`;
    const overlay=host.firstElementChild,form=overlay.querySelector('[data-maintenance-complete-form]');document.body.append(overlay);
    const close=value=>{overlay.remove();resolve(value);};overlay.querySelectorAll('[data-cancel]').forEach(button=>button.onclick=()=>close(null));overlay.onclick=event=>{if(event.target===overlay)close(null);};
    form.onsubmit=event=>{event.preventDefault();const fd=new FormData(form);close({cost:Number(fd.get('cost')||0),mileage:fd.get('mileage')?Number(fd.get('mileage')):null,notes:String(fd.get('notes')||'')});};form.elements.cost.focus();
  });
}
export function bindMaintenance(root,{user,actions}){const form=root.querySelector('#cloud-maintenance-form');root.querySelector('[data-empty-action="maintenance-create"]')?.addEventListener('click',()=>{const editor=form?.closest('details');if(editor)editor.open=true;form?.elements.vehicleId?.focus();form?.scrollIntoView({behavior:'smooth',block:'start'});});if(!can(user,'maintenance.write'))return;if(form)form.onsubmit=async event=>{event.preventDefault();const fd=new FormData(form);await actions.queue('maintenance.create',{id:`MNT-${crypto.randomUUID()}`,vehicleId:String(fd.get('vehicleId')),type:String(fd.get('type')),dueAt:brDateToIso(fd.get('dueAt'))||null,dueMileage:fd.get('dueMileage')?Number(fd.get('dueMileage')):null,costEstimate:Number(fd.get('costEstimate')||0),notes:String(fd.get('notes')||'')},'MNT');await actions.refresh('maintenance');};root.querySelectorAll('[data-maintenance-start]').forEach(button=>button.onclick=async()=>{await actions.queue('maintenance.start',{id:button.dataset.maintenanceStart},'MNT');await actions.refresh('maintenance');});root.querySelectorAll('[data-maintenance-complete]').forEach(button=>button.onclick=async()=>{const input=await openMaintenanceCompleteDialog();if(!input)return;await actions.queue('maintenance.complete',{id:button.dataset.maintenanceComplete,...input},'MNT');await actions.refresh('maintenance');});}
