import { can } from '../../domain/auth.mjs';
import { esc,money,shortDate } from './common.mjs';

function options(items,label){return (items??[]).map(item=>`<option value="${esc(item.id)}">${esc(label(item))}</option>`).join('');}
function nextStatus(status){return({reserva:'retirada',retirada:'em_uso',em_uso:'devolucao'})[status]??null;}
function nextLabel(status){return({reserva:'Confirmar retirada',retirada:'Iniciar uso',em_uso:'Registrar devolução'})[status]??'';}
function rentalStatusLabel(status){return({reserva:'Locação',retirada:'Retirada',em_uso:'Em uso',devolucao:'Devolvida'})[status]??String(status||'').replaceAll('_',' ');}
export function rentalsHtml(snapshot,user){const writable=can(user,'rental.write'),finance=can(user,'finance.write');const rows=(snapshot.rentals??[]).map(r=>{const customer=snapshot.customers.find(x=>x.id===r.customerId),vehicle=snapshot.vehicles.find(x=>x.id===r.vehicleId),next=nextStatus(r.status),paid=(r.payments??[]).reduce((sum,p)=>sum+Number(p.amount||0),0);return `<article class="card cloud-entity-card"><div><strong>${esc(vehicle?.model||r.vehicleId)} · ${esc(customer?.name||r.customerId)}</strong><small>${esc(rentalStatusLabel(r.status))} · ${r.periodMode==='continuous'?'contínua':`${shortDate(r.pickupAt)} → ${shortDate(r.returnAt)}`}</small><small>${money(r.total)} · recebido ${money(paid)} · ${esc(r.billingMode==='daily'?'por diária':'total')}</small><small>${esc(r.priority||'Média')} · ${esc(r.notes||'Sem observações')}</small></div><div class="actions">${writable&&next?`<button data-rental-advance="${esc(r.id)}" data-status="${next}">${nextLabel(r.status)}</button>`:''}${writable&&r.periodMode==='continuous'&&!r.continuousClosedAt&&r.status==='em_uso'?`<button data-rental-close="${esc(r.id)}">Encerrar diária contínua</button>`:''}${finance&&r.billingMode!=='daily'&&Number(r.total||0)>paid?`<button data-rental-pay="${esc(r.id)}" data-balance="${Math.max(0,Number(r.total||0)-paid)}">Receber</button>`:''}</div></article>`}).join('');return `<div class="heading"><div><small>CICLO COMPLETO</small><h1>Locações</h1></div></div><div class="cloud-grid">${writable?`<form id="cloud-rental-form" class="panel cloud-form" data-test="rental-form"><h2>Nova locação</h2><label>Cliente<select name="customerId" required><option value="">Selecione</option>${options(snapshot.customers,x=>x.name)}</select></label><label>Veículo<select name="vehicleId" required><option value="">Selecione</option>${options(snapshot.vehicles.filter(v=>v.availability!=='manutencao'),x=>`${x.model} · ${x.plate}`)}</select></label><label>Retirada<input name="pickupAt" type="datetime-local" required></label><label>Período<select name="periodMode"><option value="fixed">Com devolução prevista</option><option value="continuous">Sem prazo / contínua</option></select></label><label data-return-field>Devolução<input name="returnAt" type="datetime-local"></label><label>Diária<input name="dailyRate" type="number" min="0.01" step="0.01" required></label><label>Cobrança<select name="billingMode"><option value="daily">Por diária</option><option value="total">Total</option></select></label><label>Prioridade<select name="priority"><option>Baixa</option><option selected>Média</option><option>Alta</option></select></label><label class="full">Observações<textarea name="notes"></textarea></label><button class="primary full">Criar locação</button></form>`:''}<section class="panel"><h2>Locações</h2><div class="cloud-card-list">${rows||'<div class="empty">Nenhuma locação.</div>'}</div></section></div>`;}

export function bindRentals(root,{snapshot,user,actions}){const form=root.querySelector('#cloud-rental-form');if(form){const period=form.elements.periodMode,returnField=form.querySelector('[data-return-field]'),billing=form.elements.billingMode;const toggle=()=>{const continuous=period.value==='continuous';returnField.hidden=continuous;form.elements.returnAt.required=!continuous;if(continuous)billing.value='daily';billing.querySelector('option[value="total"]').disabled=continuous;};period.onchange=toggle;toggle();form.onsubmit=async event=>{event.preventDefault();const fd=new FormData(form),continuous=fd.get('periodMode')==='continuous',payload={customerId:String(fd.get('customerId')),vehicleId:String(fd.get('vehicleId')),pickupAt:new Date(String(fd.get('pickupAt'))).toISOString(),returnAt:continuous?null:new Date(String(fd.get('returnAt'))).toISOString(),periodMode:continuous?'continuous':'fixed',dailyRate:Number(fd.get('dailyRate')),billingMode:continuous?'daily':String(fd.get('billingMode')),priority:String(fd.get('priority')||'Média'),notes:String(fd.get('notes')||'')};await actions.queue('rental.create',payload,'LOC');await actions.refresh('rentals');};}
  root.querySelectorAll('[data-rental-advance]').forEach(button=>button.onclick=async()=>{await actions.queue('rental.advance',{rentalId:button.dataset.rentalAdvance,status:button.dataset.status},'ADV');await actions.refresh('rentals');});
  root.querySelectorAll('[data-rental-close]').forEach(button=>button.onclick=async()=>{const value=prompt('Informe a data/hora de devolução (AAAA-MM-DDTHH:mm):',new Date().toISOString().slice(0,16));if(!value)return;await actions.queue('rental.closeContinuous',{rentalId:button.dataset.rentalClose,returnAt:new Date(value).toISOString()},'CLOSE');await actions.refresh('rentals');});
  root.querySelectorAll('[data-rental-pay]').forEach(button=>button.onclick=async()=>{const amount=prompt('Valor recebido:',String(Number(button.dataset.balance||0).toFixed(2)));if(!amount)return;const method=prompt('Forma de pagamento:','PIX')||'PIX';await actions.queue('rental.payment',{rentalId:button.dataset.rentalPay,amount:Number(amount),method,paidAt:new Date().toISOString()},'PAY');await actions.refresh('rentals');});
}
