'use strict';
function normalizeBase(value){const url=new URL(String(value));if(!['https:','http:'].includes(url.protocol))throw new Error('replica_url_invalid');return url.origin;}
function createReplicaClient({baseUrl,sessionProvider,fetchImpl=globalThis.fetch,timeoutMs=20000}={}){if(typeof fetchImpl!=='function'||typeof sessionProvider!=='function')throw new TypeError('replica_client_dependencies_required');const base=normalizeBase(baseUrl);async function headers(){const auth=await sessionProvider(),out={'accept':'application/json','origin':base};if(auth?.deviceToken)out['x-locadora-device-token']=String(auth.deviceToken);else if(auth?.cookie)out.cookie=String(auth.cookie);return out;}async function request(pathname,{binary=false}={}){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs);try{const response=await fetchImpl(`${base}${pathname}`,{method:'GET',headers:await headers(),signal:controller.signal});if(!response.ok){let detail='';try{detail=(await response.json())?.error||'';}catch{}const error=new Error(detail||`replica_http_${response.status}`);error.status=response.status;throw error;}return binary?Buffer.from(await response.arrayBuffer()):response.json();}finally{clearTimeout(timer);}}
  return Object.freeze({
    async bootstrap(){const manifest=await request('/api/v1/replica/bootstrap'),snapshot={installations:manifest.installation?[manifest.installation]:[]},limit=Number(manifest.pageSize)||250;for(const table of manifest.tables||[]){const rows=[];let offset=0;while(true){const page=await request(`/api/v1/replica/table/${encodeURIComponent(table)}?offset=${offset}&limit=${limit}`);rows.push(...(page.rows||[]));offset=Number(page.nextOffset)||rows.length;if(!page.hasMore)break;}snapshot[table]=rows;}return{restoreGeneration:manifest.restoreGeneration,cursor:manifest.cursor,snapshot,attachments:manifest.attachments||[]};},
    changes(cursor){return request(`/api/v1/replica/changes?after=${encodeURIComponent(Number(cursor)||0)}&limit=100`);},
    attachment(id){return request(`/api/v1/attachments/${encodeURIComponent(id)}`,{binary:true});}
  });}
exports.createReplicaClient=createReplicaClient;
