import { API_PREFIX } from '../config.mjs';
import { canCloud } from '../auth/permissions.mjs';
import { listDevices,revokeDevice,revokeSessions } from '../auth/devices.mjs';
import { issueDeviceCredential } from '../auth/device-credentials.mjs';
const JSON_HEADERS={'content-type':'application/json; charset=utf-8','cache-control':'no-store'};const DEVICE_PREFIX=`${API_PREFIX}/devices`,SESSION_PREFIX=`${API_PREFIX}/sessions`;
function json(body,status=200){return new Response(JSON.stringify(body),{status,headers:JSON_HEADERS});}
async function read(request){try{return await request.json();}catch{return{};}}
export function isDeviceManagementRoute(request){const p=new URL(request.url).pathname;return p===DEVICE_PREFIX||p.startsWith(`${DEVICE_PREFIX}/`)||p===SESSION_PREFIX||p.startsWith(`${SESSION_PREFIX}/`);}
export async function handleDeviceManagementRoute(request,env,_ctx,{auth=null}={}){if(!auth)return json({ok:false,error:'unauthorized'},401);if(!canCloud(auth,'*'))return json({ok:false,error:'forbidden'},403);const p=new URL(request.url).pathname,m=request.method.toUpperCase();try{if(p===DEVICE_PREFIX&&m==='GET')return json({ok:true,devices:await listDevices(env.DB,auth.installationId)});if(p===`${DEVICE_PREFIX}/credentials`&&m==='POST'){const input=await read(request),credential=await issueDeviceCredential(env.DB,auth,input);return json({ok:true,credential},201);}const revoke=p.match(new RegExp(`^${DEVICE_PREFIX}/([^/]+)/revoke/?$`));if(revoke&&m==='POST')return json(await revokeDevice(env.DB,auth.installationId,decodeURIComponent(revoke[1])));if(p===`${SESSION_PREFIX}/revoke-others`&&m==='POST')return json({ok:true,...await revokeSessions(env.DB,auth.installationId,{exceptSessionId:auth.sessionId})});if(p===`${SESSION_PREFIX}/revoke-all`&&m==='POST')return json({ok:true,...await revokeSessions(env.DB,auth.installationId)});return json({ok:false,error:'not_found'},404);}catch(error){return json({ok:false,error:error?.message||'internal_error'},Number(error?.status)||500);}}
