import { API_PREFIX } from '../config.mjs';
import { canCloud } from '../auth/permissions.mjs';
import { BACKUP_TABLES,safeBackupTable } from '../backup/tables.mjs';
import { fetchInstallationTable } from '../backup/export-d1.mjs';
const PREFIX=`${API_PREFIX}/replica`,HEADERS={'content-type':'application/json; charset=utf-8','cache-control':'no-store'},CHANGE_TABLES=Object.freeze({
  customer:['customers'],vehicle:['vehicles'],
  rental:['rentals','vehicles','billing_plans','billing_installments','ledger'],rentalPayment:['rental_payments','rentals','ledger'],billingPayment:['billing_payments','billing_installments','rentals','ledger'],
  attachment:['attachments'],inspection:['inspections','inspection_items','vehicles'],inspectionItem:['inspection_items'],
  maintenance:['maintenance','vehicles','expenses','ledger'],expense:['expenses','ledger'],ledger:['ledger'],
  billingPlan:['billing_plans','billing_installments','ledger'],billingInstallment:['billing_installments','ledger'],collectionAction:['collection_actions'],
  contractTemplate:['contract_templates'],issuedContract:['issued_contracts'],contract:['issued_contracts'],alertState:['alert_state']
});
function json(body,status=200){return new Response(JSON.stringify(body),{status,headers:HEADERS});}
async function installation(db,id){return db.prepare('SELECT * FROM installations WHERE id=? AND deleted_at IS NULL LIMIT 1').bind(id).first();}
async function generation(db,id){return Number((await installation(db,id))?.restore_generation)||0;}
async function cursor(db,id){const row=await db.prepare('SELECT COALESCE(MAX(sequence),0) AS cursor FROM sync_changes WHERE installation_id=?').bind(id).first();return Number(row?.cursor)||0;}
export function isReplicaRoute(request){const p=new URL(request.url).pathname;return p===`${PREFIX}/bootstrap`||p.startsWith(`${PREFIX}/table/`)||p===`${PREFIX}/changes`;}
export async function handleReplicaRoute(request,env,_ctx,{auth=null}={}){if(!auth)return json({ok:false,error:'unauthorized'},401);if(!canCloud(auth,'*'))return json({ok:false,error:'forbidden'},403);if(request.method!=='GET')return json({ok:false,error:'method_not_allowed'},405);const url=new URL(request.url),p=url.pathname;try{if(p===`${PREFIX}/bootstrap`){const install=await installation(env.DB,auth.installationId),rows=await env.DB.prepare(`SELECT id,entity_type AS entityType,entity_id AS entityId,mime_type AS mimeType,size_bytes AS sizeBytes,sha256,created_by AS createdBy FROM attachments WHERE installation_id=? AND status='ready' AND deleted_at IS NULL ORDER BY id`).bind(auth.installationId).all();return json({ok:true,installation:install,restoreGeneration:Number(install?.restore_generation)||0,cursor:await cursor(env.DB,auth.installationId),tables:BACKUP_TABLES,attachments:rows?.results??[],pageSize:250});}const tableMatch=p.match(new RegExp(`^${PREFIX}/table/([^/]+)/?$`));if(tableMatch){const table=safeBackupTable(decodeURIComponent(tableMatch[1]));if(!table)return json({ok:false,error:'table_not_found'},404);const offset=Math.max(0,Number(url.searchParams.get('offset'))||0),limit=Math.min(500,Math.max(1,Number(url.searchParams.get('limit'))||250)),rows=await fetchInstallationTable(env.DB,auth.installationId,table,{offset,limit});return json({ok:true,table,rows,offset,nextOffset:offset+rows.length,hasMore:rows.length===limit});}if(p===`${PREFIX}/changes`){const after=Math.max(0,Number(url.searchParams.get('after'))||0),limit=Math.min(200,Math.max(1,Number(url.searchParams.get('limit'))||100)),result=await env.DB.prepare('SELECT sequence,operation_id AS operationId,device_id AS deviceId,entity_type AS entityType,entity_id AS entityId,operation,base_version AS baseVersion,entity_version AS entityVersion,payload_json AS payloadJson,created_at AS createdAt FROM sync_changes WHERE installation_id=? AND sequence>? ORDER BY sequence LIMIT ?').bind(auth.installationId,after,limit).all(),raw=result?.results??[],changes=raw.map(row=>({...row,payload:row.payloadJson?JSON.parse(row.payloadJson):null,payloadJson:undefined})),affected=new Set();for(const change of changes)for(const table of CHANGE_TABLES[change.entityType]||BACKUP_TABLES)affected.add(table);const tableSnapshots={};for(const table of affected){const rows=[];let offset=0;while(true){const page=await fetchInstallationTable(env.DB,auth.installationId,table,{offset,limit:500});rows.push(...page);offset+=page.length;if(page.length<500)break;}tableSnapshots[table]=rows;}const next=changes.length?Number(changes.at(-1).sequence):after;return json({ok:true,restoreGeneration:await generation(env.DB,auth.installationId),changes,cursor:next,hasMore:raw.length===limit,tableSnapshots});}return json({ok:false,error:'not_found'},404);}catch(error){console.error('replica route error',error);return json({ok:false,error:error?.message||'internal_error'},500);}}
