import { createRuntimeRepository } from './storage/repository.mjs';
import { createOfflineBlobStore } from './storage/offline-blob-store.mjs';
import { runOutbox } from './sync/outbox-runner.mjs';
import { rentalContractPdf,rentalReceiptPdf,inspectionPdf,issuedContractPdf } from './domain/documents.mjs';
import { buildCloudSnapshot,esc,navigationFor,navHtml } from './cloud/ui/common.mjs';
import { overviewHtml } from './cloud/ui/overview.mjs';
import { customersHtml,bindCustomers } from './cloud/ui/customers.mjs';
import { vehiclesHtml,bindVehicles } from './cloud/ui/vehicles.mjs';
import { rentalsHtml,bindRentals } from './cloud/ui/rentals.mjs';
import { inspectionsHtml,bindInspections } from './cloud/ui/inspections.mjs';
import { financeHtml,bindFinance } from './cloud/ui/finance.mjs';
import { billingHtml,bindBilling } from './cloud/ui/billing.mjs';
import { delinquencyHtml,bindDelinquency } from './cloud/ui/delinquency.mjs';
import { contractsHtml,bindContracts } from './cloud/ui/contracts.mjs';
import { documentsHtml,bindDocuments } from './cloud/ui/documents.mjs';
import { alertsHtml,bindAlerts } from './cloud/ui/alerts.mjs';
import { maintenanceHtml,bindMaintenance } from './cloud/ui/maintenance.mjs';

const RESOURCE_PERMISSIONS=Object.freeze({
  customers:'customer.read',vehicles:'vehicle.read',rentals:'rental.read',rentalPayments:'finance.read',expenses:'finance.read',ledger:'finance.read',
  inspections:'inspection.read',inspectionItems:'inspection.read',maintenance:'maintenance.read',billingPlans:'billing.read',billingInstallments:'billing.read',billingPayments:'billing.read',collectionActions:'billing.read',
  contractTemplates:'contracts.read',issuedContracts:'contracts.read',attachments:'documents.read',alertState:'alerts.read'
});
const DEVICE_KEY='cloud:device-id',CLOUD_INSTALLATION_ID='LOCADORA-GEORGE',GEORGE_LOGIN_EMAIL='georgedaut.adm@gmail.com';
const APPROVED_PARITY_MODULES='Visão geral · Clientes · Frota · Locações · Vistorias · Financeiro · Cobranças · Inadimplência · Contratos · Documentos · Alertas · Manutenção';
let flash='';
const uiState={editingCustomerId:null,editingVehicleId:null};

function operationId(prefix='OP'){return `${prefix}-${crypto.randomUUID()}`;}
function message(error){const code=String(error?.code??error?.message??'');if(code==='invalid_credentials'||error?.status===401)return'E-mail ou senha inválidos.';if(code==='weak_password')return'A nova senha precisa ter pelo menos 10 caracteres.';if(code==='password_change_required')return'É necessário concluir o primeiro acesso.';if(code==='version_conflict'||error?.status===409)return'Conflito detectado. A versão da nuvem não será sobrescrita automaticamente.';if(error?.status===403)return'Você não possui permissão para esta operação.';if(error instanceof TypeError||!navigator.onLine)return'Sem conexão. A operação permanece salva neste aparelho.';return error?.message&&error.message!==code?String(error.message):'Não foi possível concluir a operação.';}
async function deviceId(repository){let value=await repository.kv.get(DEVICE_KEY);if(value)return String(value);value=`WEB-${crypto.randomUUID()}`;await repository.kv.set(DEVICE_KEY,value);return value;}
function permission(user,required){if(!user?.active)return false;if(user.role==='admin')return true;const roles={atendente:new Set(['rental.read','customer.read','vehicle.read','finance.read','billing.read','contracts.read','inspection.read','maintenance.read','alerts.read','documents.read']),vistoriador:new Set(['rental.read','vehicle.read','inspection.read','maintenance.read','alerts.read','documents.read','contracts.read'])};return roles[user.role]?.has(required)??false;}
function allowedResources(user){return Object.entries(RESOURCE_PERMISSIONS).filter(([,required])=>permission(user,required)).map(([resource])=>resource);}
async function flushPending(repository,runtime){const pushed=repository.outbox?await runOutbox({outbox:repository.outbox,api:repository.api,blobs:runtime.blobs,baseRetryMs:1_500,maxRetryMs:60_000,limit:30}):null;const pulled=repository.cloudSync&&navigator.onLine?await repository.cloudSync.pullChanges():null;return{pushed,pulled};}
async function queueOperation(repository,runtime,{kind,payload,operationId:id=operationId(),optimistic=null}={}){const queued=await repository.outbox.enqueue({kind,payload,operationId:id});if(optimistic?.resource&&optimistic?.item)await repository.cache.upsertResourceItem(optimistic.resource,{...optimistic.item,_syncStatus:'pending'});if(navigator.onLine)await flushPending(repository,runtime).catch(()=>{});const current=await repository.outbox.get(queued.id);if(current?.status==='conflict')throw Object.assign(new Error('version_conflict'),{status:409,details:current.lastError});return current;}
async function loadCloudState(repository,user){const resources=allowedResources(user),data={};let online=navigator.onLine,lastError=null;for(const resource of resources){try{data[resource]=await repository.query(resource,{allowCachedOnError:true});}catch(error){if(error?.status===403){data[resource]=await repository.cache.getResource(resource);continue;}online=false;lastError=message(error);data[resource]=await repository.cache.getResource(resource);}}return{resources,data,online:online&&repository.status().online!==false,lastError:lastError??repository.status().lastError};}
function statusText(queue,online,session){const pending=queue.pending+queue.sending+queue.failed;if(queue.conflict)return'Conflito';if(!online&&pending)return'Salvo neste aparelho';if(session?._offlineSession)return'Sessão local';if(!online)return'Salvo neste aparelho';if(pending)return'Pendente de sincronização';return'Sincronizado';}
function conflictHtml(conflicts){if(!conflicts.length)return'';return `<section class="panel" data-test="cloud-conflicts"><h2>Conflitos de sincronização</h2><p>A alteração local ficou preservada. O sistema não sobrescreve uma versão mais nova da nuvem automaticamente.</p>${conflicts.map(item=>`<article class="card"><strong>${esc(item.kind)}</strong><p class="hint">Alteração deste aparelho</p><pre>${esc(JSON.stringify(item.payload,null,2))}</pre><p class="hint">Versão atual da nuvem</p><pre>${esc(JSON.stringify(item.lastError?.details?.current??null,null,2))}</pre><button type="button" class="secondary" data-cloud-accept="${esc(item.id)}">Usar versão da nuvem</button></article>`).join('')}</section>`;}
function pdf(name,bytes){const blob=new Blob([bytes],{type:'application/pdf'}),url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=name;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),0);}

const VIEW_HTML=Object.freeze({overview:(snapshot,user)=>overviewHtml(snapshot),customers:customersHtml,vehicles:vehiclesHtml,rentals:rentalsHtml,inspections:inspectionsHtml,finance:financeHtml,billing:billingHtml,delinquency:delinquencyHtml,contracts:contractsHtml,documents:documentsHtml,alerts:alertsHtml,maintenance:maintenanceHtml});
const VIEW_BIND=Object.freeze({customers:bindCustomers,vehicles:bindVehicles,rentals:bindRentals,inspections:bindInspections,finance:bindFinance,billing:bindBilling,delinquency:bindDelinquency,contracts:bindContracts,documents:bindDocuments,alerts:bindAlerts,maintenance:bindMaintenance});

function renderLogin(app,repository,runtime,{error='',firstAccess=false,username=GEORGE_LOGIN_EMAIL,currentPassword=''}={}){app.innerHTML=`<div class="login-wrap"><form id="cloud-login" class="login-card"><div class="brand big"><span class="brandmark">LV</span><div><small>ARTISYS</small><strong>Sistema Locadora George</strong></div></div><h1>${firstAccess?'Primeiro acesso':'Acesso online'}</h1><label>E-mail<input name="username" type="email" autocomplete="username" value="${esc(username)}" required></label><label>${firstAccess?'Senha atual':'Senha'}<input name="password" type="password" autocomplete="current-password" value="${esc(currentPassword)}" required></label>${firstAccess?'<label>Nova senha<input name="newPassword" type="password" autocomplete="new-password" minlength="10" required></label>':''}<button class="primary">${firstAccess?'Definir senha e entrar':'Entrar'}</button><p class="hint">A sessão é validada pelo servidor. Operações offline ficam salvas neste aparelho.</p><p id="cloud-login-error" class="error">${esc(error)}</p></form></div>`;app.querySelector('#cloud-login').onsubmit=async event=>{event.preventDefault();const form=event.currentTarget,fd=new FormData(form),identity={installationId:CLOUD_INSTALLATION_ID,username:String(fd.get('username')??'').trim().toLowerCase()},password=String(fd.get('password')??''),errorNode=app.querySelector('#cloud-login-error');errorNode.textContent='';form.querySelector('button').disabled=true;try{const id=await deviceId(repository),result=firstAccess?await repository.api.firstAccess({...identity,currentPassword:password,newPassword:String(fd.get('newPassword')??''),deviceId:id}):await repository.api.login({...identity,password,deviceId:id});await repository.setSession(result);await flushPending(repository,runtime).catch(()=>{});await renderCloudHome(app,repository,runtime,{...result,_offlineSession:false},'overview');}catch(loginError){if(loginError?.code==='password_change_required')return renderLogin(app,repository,runtime,{firstAccess:true,username:identity.username,currentPassword:password});errorNode.textContent=message(loginError);form.querySelector('button').disabled=false;}};}

function actionsFor(app,repository,runtime,session,view,snapshot){const refresh=async(target=view)=>renderCloudHome(app,repository,runtime,session,target);return{
  refresh,
  async queue(kind,payload,prefix='OP',optimistic=null){try{const result=await queueOperation(repository,runtime,{kind,payload,operationId:operationId(prefix),optimistic});flash=navigator.onLine?'Operação salva e sincronizada.':'Operação salva neste aparelho.';return result;}catch(error){flash=message(error);await refresh(view);throw error;}},
  async createEntity(resource,data){const singular=resource==='customers'?'customer':'vehicle',id=data.id||`${singular==='customer'?'CUS':'VEI'}-${crypto.randomUUID()}`,payload={...data,id};return this.queue(`${singular}.create`,payload,singular.toUpperCase(),{resource,item:{...payload,version:0}});},
  async updateEntity(resource,id,data,expectedVersion){const singular=resource==='customers'?'customer':'vehicle';return this.queue(`${singular}.update`,{id,data,expectedVersion},'UPD');},
  async deleteEntity(resource,id,expectedVersion){const singular=resource==='customers'?'customer':'vehicle';return this.queue(`${singular}.delete`,{id,expectedVersion},'DEL');},
  async uploadFile(file,entityType,entityId){if(!(file instanceof Blob)||!file.size)throw new Error('Arquivo inválido.');const attachmentId=`ATT-${crypto.randomUUID()}`;await runtime.blobs.put(attachmentId,file,{entityType,entityId,mimeType:file.type||'application/octet-stream',fileName:file.name||'arquivo'});await repository.outbox.enqueue({kind:'attachment.upload',operationId:operationId('ATT'),payload:{attachmentId}});return attachmentId;},
  async flush(){if(navigator.onLine)return flushPending(repository,runtime);return null;},
  downloadRentalContract:(id,current=snapshot)=>pdf(`contrato-${id}.pdf`,rentalContractPdf(current,id)),
  downloadRentalReceipt:(id,current=snapshot)=>pdf(`recibo-${id}.pdf`,rentalReceiptPdf(current,id)),
  downloadInspectionPdf:(id,current=snapshot)=>pdf(`vistoria-${id}.pdf`,inspectionPdf(current,id)),
  downloadIssuedPdf:(id,current=snapshot)=>pdf(`contrato-emitido-${id}.pdf`,issuedContractPdf(current,id))
};}

async function bindView(app,repository,runtime,session,view,state,snapshot){for(const button of app.querySelectorAll('[data-cloud-nav]'))button.onclick=()=>void renderCloudHome(app,repository,runtime,session,button.dataset.cloudNav);for(const button of app.querySelectorAll('[data-cloud-accept]'))button.onclick=async()=>{try{await repository.outbox.resolveConflict(button.dataset.cloudAccept,{strategy:'accept-cloud'});if(repository.cloudSync&&navigator.onLine)await repository.cloudSync.pullChanges();flash='Versão da nuvem aplicada.';await renderCloudHome(app,repository,runtime,session,view);}catch(error){flash=message(error);await renderCloudHome(app,repository,runtime,session,view);}};const binder=VIEW_BIND[view];if(binder)binder(app,{snapshot,user:session.user,actions:actionsFor(app,repository,runtime,session,view,snapshot),state:uiState,data:state.data});}

async function renderCloudHome(app,repository,runtime,session,requestedView='overview'){const user=session?.user;if(!user)return renderLogin(app,repository,runtime);const navigation=navigationFor(user),view=navigation.some(item=>item.id===requestedView)?requestedView:'overview';app.innerHTML='<div class="login-wrap"><div class="login-card"><strong>Carregando…</strong></div></div>';const state=await loadCloudState(repository,user),snapshot=buildCloudSnapshot(state.data),queue=await repository.outbox.summary(),conflicts=await repository.outbox.list({statuses:['conflict']}),cursor=repository.cloudSync?await repository.cloudSync.getCursor():0,pending=queue.pending+queue.sending+queue.failed,status=statusText(queue,state.online,session),sessionLabel=session?._offlineSession?'Sessão local · aguardando validação':'Sessão validada pelo servidor',title=navigation.find(item=>item.id===view)?.label||'Visão geral',renderer=VIEW_HTML[view]??VIEW_HTML.overview;app.innerHTML=`<div class="shell cloud-shell"><aside class="sidebar cloud-nav"><div class="brand"><span class="brandmark">LV</span><div><small>SISTEMA</small><strong>LOCADORA GEORGE</strong></div></div><nav>${navHtml(user,view)}</nav><div class="session"><strong>${esc(user.name||user.username)}</strong><small>${esc(user.role)}</small><button id="cloud-logout">Sair</button></div></aside><main><header class="topbar cloud-statusbar"><strong id="cloud-sync-state" data-test="sync-state">${esc(status)}</strong><span>${esc(sessionLabel)}</span><span>${pending} pendência(s)</span><span>${queue.conflict} conflito(s)</span><span>Delta #${cursor}</span></header><section class="content"><div class="page-head"><div><h1>${esc(title)}</h1><p>Operação mobile com D1/R2 e fila offline durável.</p></div><div><button id="cloud-sync" class="secondary">Sincronizar</button><button id="cloud-refresh" class="primary">Atualizar</button></div></div>${flash?`<p class="cloud-flash" data-test="flash">${esc(flash)}</p>`:''}${state.lastError?`<p class="hint">${esc(state.lastError)}</p>`:''}${conflictHtml(conflicts)}${renderer(snapshot,user,{editingId:view==='customers'?uiState.editingCustomerId:view==='vehicles'?uiState.editingVehicleId:null})}</section></main></div>`;flash='';app.querySelector('#cloud-refresh').onclick=()=>void renderCloudHome(app,repository,runtime,session,view);app.querySelector('#cloud-sync').onclick=async()=>{await flushPending(repository,runtime).catch(()=>{});await renderCloudHome(app,repository,runtime,session,view);};app.querySelector('#cloud-logout').onclick=async()=>{try{await repository.api.logout();}catch{}await repository.clearSession();renderLogin(app,repository,runtime);};await bindView(app,repository,runtime,session,view,state,snapshot);}

export async function bootstrapCloudApp({app=document.querySelector('#app'),baseUrl=location.origin}={}){if(!app)throw new Error('app_root_missing');void APPROVED_PARITY_MODULES;app.innerHTML='<div class="login-wrap"><div class="login-card"><strong>Inicializando acesso online…</strong><p class="hint">Preparando cache e fila offline.</p></div></div>';const repository=await createRuntimeRepository({mode:'cloud',baseUrl}),runtime={blobs:createOfflineBlobStore()};if('serviceWorker' in navigator&&globalThis.isSecureContext){try{await navigator.serviceWorker.register('./sw.js');}catch{}}window.addEventListener('online',()=>{void (async()=>{try{const live=await repository.api.session();await repository.setSession(live);await flushPending(repository,runtime).catch(()=>{});const active=document.querySelector('[data-cloud-nav].active')?.dataset.cloudNav||'overview';await renderCloudHome(app,repository,runtime,{...live,_offlineSession:false},active);}catch(error){if(error?.status===401){await repository.clearSession();renderLogin(app,repository,runtime);}}})();});const cached=await repository.session();try{const live=await repository.api.session();await repository.setSession(live);await flushPending(repository,runtime).catch(()=>{});return renderCloudHome(app,repository,runtime,{...live,_offlineSession:false},'overview');}catch(error){if(error?.status===401){await repository.clearSession();return renderLogin(app,repository,runtime);}if(cached?.user)return renderCloudHome(app,repository,runtime,{...cached,_offlineSession:true},'overview');return renderLogin(app,repository,runtime,{error:message(error)});}}
