import { can } from './domain/auth.mjs';
import { createRuntimeRepository } from './storage/repository.mjs';
import { createOfflineBlobStore } from './storage/offline-blob-store.mjs';
import { runOutbox } from './sync/outbox-runner.mjs';

const RESOURCE_PERMISSIONS=Object.freeze({customers:'customer.read',vehicles:'vehicle.read',rentals:'rental.read',expenses:'finance.read',inspections:'inspection.read',maintenance:'maintenance.read',billingInstallments:'billing.read'});
const DEVICE_KEY='cloud:device-id';
const CLOUD_INSTALLATION_ID='LOCADORA-GEORGE',GEORGE_LOGIN_EMAIL='georgedaut.adm@gmail.com';
const NAV=Object.freeze([['overview','Visão geral'],['customers','Clientes'],['vehicles','Frota'],['rentals','Locações'],['inspections','Vistorias'],['finance','Financeiro']]);
let flash='';
function esc(value){return String(value??'').replace(/[&<>\"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[char]));}
function money(value){return Number(value||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});}
function operationId(prefix='OP'){return `${prefix}-${crypto.randomUUID()}`;}
function message(error){const code=String(error?.code??error?.message??'');if(code==='invalid_credentials'||error?.status===401)return'E-mail ou senha inválidos.';if(code==='weak_password')return'A nova senha precisa ter pelo menos 10 caracteres.';if(code==='password_change_required')return'É necessário concluir o primeiro acesso.';if(code==='version_conflict'||error?.status===409)return'Conflito detectado. A versão da nuvem não será sobrescrita automaticamente.';if(error instanceof TypeError||!navigator.onLine)return'Sem conexão. A operação permanece salva neste aparelho.';return error?.message&&error.message!==code?String(error.message):'Não foi possível concluir a operação.';}
async function deviceId(repository){let value=await repository.kv.get(DEVICE_KEY);if(value)return String(value);value=`WEB-${crypto.randomUUID()}`;await repository.kv.set(DEVICE_KEY,value);return value;}
function allowedResources(user){return Object.entries(RESOURCE_PERMISSIONS).filter(([,permission])=>can(user,permission)).map(([resource])=>resource);}
async function flushPending(repository,runtime){const pushed=repository.outbox?await runOutbox({outbox:repository.outbox,api:repository.api,blobs:runtime.blobs,baseRetryMs:1_500,maxRetryMs:60_000,limit:30}):null;const pulled=repository.cloudSync&&navigator.onLine?await repository.cloudSync.pullChanges():null;return{pushed,pulled};}
async function queueOperation(repository,runtime,{kind,payload,operationId:id=operationId(),optimistic=null}={}){
  const queued=await repository.outbox.enqueue({kind,payload,operationId:id});if(optimistic?.resource&&optimistic?.item)await repository.cache.upsertResourceItem(optimistic.resource,{...optimistic.item,_syncStatus:'pending'});
  if(navigator.onLine)await flushPending(repository,runtime).catch(()=>{});const current=await repository.outbox.get(queued.id);if(current?.status==='conflict')throw Object.assign(new Error('version_conflict'),{status:409,details:current.lastError});return current;
}
async function loadCloudState(repository,user){const resources=allowedResources(user),data={};let online=navigator.onLine,lastError=null;for(const resource of resources){try{data[resource]=await repository.query(resource,{allowCachedOnError:true});}catch(error){if(error?.status===403){data[resource]=await repository.cache.getResource(resource);continue;}online=false;lastError=message(error);data[resource]=await repository.cache.getResource(resource);}}return{resources,data,online:online&&repository.status().online!==false,lastError:lastError??repository.status().lastError};}
function statusText(queue,online,session){const pending=queue.pending+queue.sending+queue.failed;if(queue.conflict)return'Conflito';if(!online&&pending)return'Salvo neste aparelho';if(session?._offlineSession)return'Sessão local';if(!online)return'Salvo neste aparelho';if(pending)return'Pendente de sincronização';return'Sincronizado';}
function navHtml(active){return NAV.map(([id,label])=>`<button type="button" data-cloud-nav="${id}" class="nav ${active===id?'active':''}">${label}</button>`).join('');}
function conflictHtml(conflicts){if(!conflicts.length)return'';return `<section class="panel" data-test="cloud-conflicts"><h2>Conflitos de sincronização</h2><p>A alteração local ficou preservada. O sistema não sobrescreve uma versão mais nova da nuvem automaticamente.</p>${conflicts.map(item=>`<article class="card"><strong>${esc(item.kind)}</strong><p class="hint">Alteração deste aparelho</p><pre>${esc(JSON.stringify(item.payload,null,2))}</pre><p class="hint">Versão atual da nuvem</p><pre>${esc(JSON.stringify(item.lastError?.details?.current??null,null,2))}</pre><button type="button" class="secondary" data-cloud-accept="${esc(item.id)}">Usar versão da nuvem</button></article>`).join('')}</section>`;}

function overviewHtml(data){const count=name=>(data[name]??[]).length;return `<div class="cards cloud-cards"><article class="card"><small>Clientes</small><strong>${count('customers')}</strong></article><article class="card"><small>Veículos</small><strong>${count('vehicles')}</strong></article><article class="card"><small>Locações</small><strong>${count('rentals')}</strong></article><article class="card"><small>Diárias</small><strong>${count('billingInstallments')}</strong></article><article class="card"><small>Vistorias</small><strong>${count('inspections')}</strong></article></div><div class="panel"><h2>Operação independente do PC</h2><p>Esta PWA usa Worker + D1/R2. O computador pode estar desligado; alterações sem internet ficam na fila deste aparelho.</p></div>`;}
function customersHtml(data){const rows=(data.customers??[]).map(x=>`<li><strong>${esc(x.name)}</strong><small>${esc(x.phone||'Sem telefone')}${x._syncStatus?' · pendente':''}</small></li>`).join('');return `<div class="cloud-grid"><form id="cloud-customer-form" class="panel cloud-form" data-test="customer-form"><h2>Novo cliente</h2><label>Nome<input name="name" required></label><label>Telefone<input name="phone" inputmode="tel"></label><label>Documento<input name="document"></label><button class="primary">Salvar cliente</button></form><section class="panel"><h2>Clientes</h2><ul class="cloud-list">${rows||'<li>Nenhum cliente.</li>'}</ul></section></div>`;}
function vehiclesHtml(data){const rows=(data.vehicles??[]).map(x=>`<li><strong>${esc(x.model)} · ${esc(x.plate)}</strong><small>${money(x.dailyRate)} / diária${x._syncStatus?' · pendente':''}</small></li>`).join('');return `<div class="cloud-grid"><form id="cloud-vehicle-form" class="panel cloud-form" data-test="vehicle-form"><h2>Novo veículo</h2><label>Modelo<input name="model" required></label><label>Placa<input name="plate" required></label><label>Diária<input name="dailyRate" type="number" min="0.01" step="0.01" required></label><button class="primary">Salvar veículo</button></form><section class="panel"><h2>Frota</h2><ul class="cloud-list">${rows||'<li>Nenhum veículo.</li>'}</ul></section></div>`;}
function options(items,label){return (items??[]).map(x=>`<option value="${esc(x.id)}">${esc(label(x))}</option>`).join('');}
function rentalsHtml(data){const rows=(data.rentals??[]).map(x=>`<li data-rental-id="${esc(x.id)}"><strong>${esc(x.status)} · ${money(x.total)}</strong><small>${esc(x.billingMode==='daily'?'Recebimento por diária':'Pagamento total')} · ${esc(x.pickupAt?.slice(0,10)||'')}</small></li>`).join('');return `<div class="cloud-grid"><form id="cloud-rental-form" class="panel cloud-form" data-test="rental-form"><h2>Nova locação</h2><label>Cliente<select name="customerId" required><option value="">Selecione</option>${options(data.customers,x=>x.name)}</select></label><label>Veículo<select name="vehicleId" required><option value="">Selecione</option>${options(data.vehicles,x=>`${x.model} · ${x.plate}`)}</select></label><label>Retirada<input name="pickupAt" type="datetime-local" required></label><label>Devolução<input name="returnAt" type="datetime-local" required></label><label>Valor da diária<input name="dailyRate" type="number" min="0.01" step="0.01" required></label><label>Cobrança<select name="billingMode"><option value="daily">Por diária</option><option value="total">Total</option></select></label><button class="primary">Criar locação</button></form><section class="panel"><h2>Locações</h2><ul class="cloud-list">${rows||'<li>Nenhuma locação.</li>'}</ul></section></div>`;}
function inspectionsHtml(data){const rows=(data.inspections??[]).map(x=>`<li><strong>${x.kind==='return'?'Devolução':'Retirada'} · ${esc(x.status)}</strong><small>${esc(x.rentalId)}${x._syncStatus?' · pendente':''}</small></li>`).join('');return `<div class="cloud-grid"><form id="cloud-inspection-form" class="panel cloud-form" data-test="inspection-form"><h2>Nova vistoria</h2><label>Locação<select name="rentalId" required><option value="">Selecione</option>${options(data.rentals,x=>`${x.id.slice(0,12)} · ${money(x.total)}`)}</select></label><label>Tipo<select name="kind"><option value="pickup">Retirada</option><option value="return">Devolução</option></select></label><label>Quilometragem<input name="mileage" type="number" min="0" step="1"></label><label>Combustível<input name="fuelLevel" placeholder="Ex.: 3/4"></label><label>Observações<textarea name="notes"></textarea></label><label>Foto<input name="photo" type="file" accept="image/jpeg,image/png,image/webp"></label><button class="primary">Salvar vistoria</button></form><section class="panel"><h2>Vistorias</h2><ul class="cloud-list">${rows||'<li>Nenhuma vistoria.</li>'}</ul></section></div>`;}
function financeHtml(data){const open=(data.billingInstallments??[]).filter(x=>!['paid','cancelled'].includes(x.status)),rows=(data.billingInstallments??[]).map(x=>`<li data-installment-id="${esc(x.id)}"><strong>Diária ${Number(x.sequence)} · ${money(x.amount)}</strong><small>Recebido ${money(x.paidAmount)} · ${esc(x.status)}</small></li>`).join('');return `<div class="cloud-grid"><form id="cloud-payment-form" class="panel cloud-form" data-test="payment-form"><h2>Receber diária</h2><label>Diária<select name="installmentId" required><option value="">Selecione</option>${options(open,x=>`#${x.sequence} · ${money(Number(x.amount)-Number(x.paidAmount||0))}`)}</select></label><label>Valor<input name="amount" type="number" min="0.01" step="0.01" required></label><label>Forma<select name="method"><option>PIX</option><option>Dinheiro</option><option>Cartão</option></select></label><button class="primary">Registrar recebimento</button></form><section class="panel"><h2>Controle de diárias</h2><ul class="cloud-list">${rows||'<li>Nenhuma diária gerada.</li>'}</ul></section></div>`;}
function viewHtml(view,data){if(view==='customers')return customersHtml(data);if(view==='vehicles')return vehiclesHtml(data);if(view==='rentals')return rentalsHtml(data);if(view==='inspections')return inspectionsHtml(data);if(view==='finance')return financeHtml(data);return overviewHtml(data);}

function renderLogin(app,repository,runtime,{error='',firstAccess=false,username=GEORGE_LOGIN_EMAIL,currentPassword=''}={}){
  app.innerHTML=`<div class="login-wrap"><form id="cloud-login" class="login-card"><div class="brand big"><span class="brandmark">LV</span><div><small>ARTISYS</small><strong>Sistema Locadora George</strong></div></div><h1>${firstAccess?'Primeiro acesso':'Acesso online'}</h1><label>E-mail<input name="username" type="email" autocomplete="username" value="${esc(username)}" required></label><label>${firstAccess?'Senha atual':'Senha'}<input name="password" type="password" autocomplete="current-password" value="${esc(currentPassword)}" required></label>${firstAccess?'<label>Nova senha<input name="newPassword" type="password" autocomplete="new-password" minlength="10" required></label>':''}<button class="primary">${firstAccess?'Definir senha e entrar':'Entrar'}</button><p class="hint">A sessão é validada pelo servidor. Operações offline ficam salvas neste aparelho.</p><p id="cloud-login-error" class="error">${esc(error)}</p></form></div>`;
  app.querySelector('#cloud-login').onsubmit=async event=>{event.preventDefault();const form=event.currentTarget,fd=new FormData(form),identity={installationId:CLOUD_INSTALLATION_ID,username:String(fd.get('username')??'').trim().toLowerCase()},password=String(fd.get('password')??''),errorNode=app.querySelector('#cloud-login-error');errorNode.textContent='';form.querySelector('button').disabled=true;try{const id=await deviceId(repository),result=firstAccess?await repository.api.firstAccess({...identity,currentPassword:password,newPassword:String(fd.get('newPassword')??''),deviceId:id}):await repository.api.login({...identity,password,deviceId:id});await repository.setSession(result);await flushPending(repository,runtime).catch(()=>{});await renderCloudHome(app,repository,runtime,{...result,_offlineSession:false},'overview');}catch(loginError){if(loginError?.code==='password_change_required')return renderLogin(app,repository,runtime,{firstAccess:true,username:identity.username,currentPassword:password});errorNode.textContent=message(loginError);form.querySelector('button').disabled=false;}};
}

async function bindView(app,repository,runtime,session,view,state){
  for(const button of app.querySelectorAll('[data-cloud-nav]'))button.onclick=()=>void renderCloudHome(app,repository,runtime,session,button.dataset.cloudNav);
  for(const button of app.querySelectorAll('[data-cloud-accept]'))button.onclick=async()=>{try{await repository.outbox.resolveConflict(button.dataset.cloudAccept,{strategy:'accept-cloud'});if(repository.cloudSync&&navigator.onLine)await repository.cloudSync.pullChanges();flash='Versão da nuvem aplicada.';await renderCloudHome(app,repository,runtime,session,view);}catch(error){flash=message(error);await renderCloudHome(app,repository,runtime,session,view);}};
  const customer=app.querySelector('#cloud-customer-form');if(customer)customer.onsubmit=async e=>{e.preventDefault();const fd=new FormData(customer),id=`CUS-${crypto.randomUUID()}`,payload={id,name:String(fd.get('name')),phone:String(fd.get('phone')||''),document:String(fd.get('document')||''),active:1};await queueOperation(repository,runtime,{kind:'customer.create',payload,operationId:operationId('CUS'),optimistic:{resource:'customers',item:{...payload,version:0}}});flash=navigator.onLine?'Cliente salvo e sincronizado.':'Cliente salvo neste aparelho.';await renderCloudHome(app,repository,runtime,session,'customers');};
  const vehicle=app.querySelector('#cloud-vehicle-form');if(vehicle)vehicle.onsubmit=async e=>{e.preventDefault();const fd=new FormData(vehicle),id=`VEI-${crypto.randomUUID()}`,payload={id,model:String(fd.get('model')),plate:String(fd.get('plate')).toUpperCase(),dailyRate:Number(fd.get('dailyRate')),availability:'disponivel'};await queueOperation(repository,runtime,{kind:'vehicle.create',payload,operationId:operationId('VEI'),optimistic:{resource:'vehicles',item:{...payload,version:0}}});flash=navigator.onLine?'Veículo salvo e sincronizado.':'Veículo salvo neste aparelho.';await renderCloudHome(app,repository,runtime,session,'vehicles');};
  const rental=app.querySelector('#cloud-rental-form');if(rental)rental.onsubmit=async e=>{e.preventDefault();const fd=new FormData(rental),toIso=value=>new Date(String(value)).toISOString(),payload={customerId:String(fd.get('customerId')),vehicleId:String(fd.get('vehicleId')),pickupAt:toIso(fd.get('pickupAt')),returnAt:toIso(fd.get('returnAt')),dailyRate:Number(fd.get('dailyRate')),periodMode:'fixed',billingMode:String(fd.get('billingMode'))};await queueOperation(repository,runtime,{kind:'rental.create',payload,operationId:operationId('LOC')});flash=navigator.onLine?'Locação salva e sincronizada.':'Locação salva neste aparelho e será criada quando houver conexão.';await renderCloudHome(app,repository,runtime,session,'rentals');};
  const inspection=app.querySelector('#cloud-inspection-form');if(inspection)inspection.onsubmit=async e=>{e.preventDefault();const fd=new FormData(inspection),id=`VIS-${crypto.randomUUID()}`,payload={id,rentalId:String(fd.get('rentalId')),kind:String(fd.get('kind')),mileage:fd.get('mileage')?Number(fd.get('mileage')):null,fuelLevel:String(fd.get('fuelLevel')||''),notes:String(fd.get('notes')||''),items:[{key:'geral',label:'Verificação geral',done:true}]};await queueOperation(repository,runtime,{kind:'inspection.create',payload,operationId:operationId('VIS'),optimistic:{resource:'inspections',item:{...payload,status:'completed',version:0}}});const file=fd.get('photo');if(file instanceof File&&file.size){const attachmentId=`ATT-${crypto.randomUUID()}`;await runtime.blobs.put(attachmentId,file,{entityType:'inspection',entityId:id,mimeType:file.type,fileName:file.name});await repository.outbox.enqueue({kind:'attachment.upload',operationId:operationId('ATT'),payload:{attachmentId}});if(navigator.onLine)await flushPending(repository,runtime).catch(()=>{});}flash=navigator.onLine?'Vistoria e evidência salvas.':'Vistoria e foto salvas neste aparelho.';await renderCloudHome(app,repository,runtime,session,'inspections');};
  const payment=app.querySelector('#cloud-payment-form');if(payment)payment.onsubmit=async e=>{e.preventDefault();const fd=new FormData(payment),payload={installmentId:String(fd.get('installmentId')),amount:Number(fd.get('amount')),method:String(fd.get('method')),paidAt:new Date().toISOString()};await queueOperation(repository,runtime,{kind:'billing.payment',payload,operationId:operationId('PAG')});flash=navigator.onLine?'Recebimento sincronizado.':'Recebimento salvo neste aparelho.';await renderCloudHome(app,repository,runtime,session,'finance');};
  const installmentSelect=app.querySelector('#cloud-payment-form select[name="installmentId"]');if(installmentSelect)installmentSelect.onchange=()=>{const item=(state.data.billingInstallments??[]).find(x=>x.id===installmentSelect.value),amount=app.querySelector('#cloud-payment-form input[name="amount"]');if(item&&amount)amount.value=String(Math.max(0,Number(item.amount)-Number(item.paidAmount||0)));};
}

async function renderCloudHome(app,repository,runtime,session,view='overview'){
  const user=session?.user;if(!user)return renderLogin(app,repository,runtime);app.innerHTML='<div class="login-wrap"><div class="login-card"><strong>Carregando…</strong></div></div>';const state=await loadCloudState(repository,user),queue=await repository.outbox.summary(),conflicts=await repository.outbox.list({statuses:['conflict']}),cursor=repository.cloudSync?await repository.cloudSync.getCursor():0,pending=queue.pending+queue.sending+queue.failed,status=statusText(queue,state.online,session),sessionLabel=session?._offlineSession?'Sessão local · aguardando validação':'Sessão validada pelo servidor';
  app.innerHTML=`<div class="shell cloud-shell"><aside class="sidebar cloud-nav"><div class="brand"><span class="brandmark">LV</span><div><small>SISTEMA</small><strong>LOCADORA GEORGE</strong></div></div><nav>${navHtml(view)}</nav><div class="session"><strong>${esc(user.name||user.username)}</strong><small>${esc(user.role)}</small><button id="cloud-logout">Sair</button></div></aside><main><header class="topbar cloud-statusbar"><strong id="cloud-sync-state" data-test="sync-state">${esc(status)}</strong><span>${esc(sessionLabel)}</span><span>${pending} pendência(s)</span><span>${queue.conflict} conflito(s)</span><span>Delta #${cursor}</span></header><section class="content"><div class="page-head"><div><h1>${esc(NAV.find(([id])=>id===view)?.[1]||'Visão geral')}</h1><p>Operação mobile com D1/R2 e fila offline durável.</p></div><div><button id="cloud-sync" class="secondary">Sincronizar</button><button id="cloud-refresh" class="primary">Atualizar</button></div></div>${flash?`<p class="cloud-flash" data-test="flash">${esc(flash)}</p>`:''}${state.lastError?`<p class="hint">${esc(state.lastError)}</p>`:''}${conflictHtml(conflicts)}${viewHtml(view,state.data)}</section></main></div>`;flash='';
  app.querySelector('#cloud-refresh').onclick=()=>void renderCloudHome(app,repository,runtime,session,view);app.querySelector('#cloud-sync').onclick=async()=>{await flushPending(repository,runtime).catch(()=>{});await renderCloudHome(app,repository,runtime,session,view);};app.querySelector('#cloud-logout').onclick=async()=>{try{await repository.api.logout();}catch{}await repository.clearSession();renderLogin(app,repository,runtime);};await bindView(app,repository,runtime,session,view,state);
}

export async function bootstrapCloudApp({app=document.querySelector('#app'),baseUrl=location.origin}={}){
  if(!app)throw new Error('app_root_missing');app.innerHTML='<div class="login-wrap"><div class="login-card"><strong>Inicializando acesso online…</strong><p class="hint">Preparando cache e fila offline.</p></div></div>';const repository=await createRuntimeRepository({mode:'cloud',baseUrl}),runtime={blobs:createOfflineBlobStore()};if('serviceWorker' in navigator&&globalThis.isSecureContext){try{await navigator.serviceWorker.register('./sw.js');}catch{}}
  window.addEventListener('online',()=>{void flushPending(repository,runtime).then(()=>{const button=document.querySelector('#cloud-sync');if(button)button.click();}).catch(()=>{});});const cached=await repository.session();try{const live=await repository.api.session();await repository.setSession(live);await flushPending(repository,runtime).catch(()=>{});return renderCloudHome(app,repository,runtime,{...live,_offlineSession:false},'overview');}catch(error){if(error?.status===401){await repository.clearSession();return renderLogin(app,repository,runtime);}if(cached?.user)return renderCloudHome(app,repository,runtime,{...cached,_offlineSession:true},'overview');return renderLogin(app,repository,runtime,{error:message(error)});}
}
